const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..")
const installer = fs.readFileSync(path.join(root, "src/lib/cloudflare-worker-installer.ts"), "utf8")
const db = fs.readFileSync(path.join(root, "src/lib/db.ts"), "utf8")
const route = fs.readFileSync(path.join(root, "src/app/api/workers/cloudflare-install/route.ts"), "utf8")
const workersPage = fs.readFileSync(path.join(root, "src/app/dashboard/workers/page.tsx"), "utf8")
const hosting = fs.readFileSync(path.join(root, "src/components/dashboard/cloudflare-worker-hosting.tsx"), "utf8")
const settingsPage = fs.readFileSync(path.join(root, "src/app/dashboard/settings/page.tsx"), "utf8")
const workflow = fs.readFileSync(path.join(root, ".github/workflows/worker-release.yml"), "utf8")
const { runtimeHealthError } = require(path.join(root, "src/lib/cloudflare-worker-health.cjs"))

test("Worker readiness rejects durable runtime errors without confusing them with deployment presence", () => {
  assert.equal(runtimeHealthError({ ok: true, state: { status: "idle" } }), null)
  assert.equal(runtimeHealthError({ ok: true, state: null }), null)
  assert.equal(runtimeHealthError({ ok: true, state: { status: "error", last_error: "Panel reconciliation failed (401)" } }), "Panel reconciliation failed (401)")
  assert.equal(runtimeHealthError({ ok: true, state: { status: "error", last_error: "Panel delivery reconciliation reported errors" } }), null)
  assert.equal(runtimeHealthError({ ok: true, state: { status: "failed", lastError: "database unavailable" } }), "database unavailable")
  assert.equal(runtimeHealthError({ ok: false, error: "not configured" }), "not configured")
  assert.match(runtimeHealthError("not-json"), /invalid status response/)
  assert.match(installer, /Runtime verification failed: \$\{healthError\}/)
  assert.match(installer, /current\.deployed = scriptPresent; current\.verified = false/)
})

test("installer deploys in dependency order and saves configuration before enabling", () => {
  assert.match(installer, /const ORDER: HostedWorker\[\] = \["backend", "scanner", "migration"\]/)
  const upload = installer.indexOf("for (const worker of ORDER)", installer.indexOf("queues_ready"))
  const save = installer.indexOf("configuration_saved")
  const verify = installer.indexOf("await verify", save)
  const schedules = installer.indexOf('state.step = "schedules_ready"', verify)
  const synchronize = installer.indexOf("await syncAllGitHubWorkerSecretsWithinInstallerLock({", schedules)
  const enable = installer.indexOf("saveRuntimeConfiguration(state, true)", verify)
  assert.ok(upload > 0 && upload < save && save < verify && verify < schedules && schedules < synchronize && synchronize < enable)
  const scheduling = installer.indexOf('state.step = "schedules_configuring"', verify)
  const scheduleLoop = installer.indexOf("await ensureSchedule(tokens[worker]", scheduling)
  assert.ok(scheduling > verify && scheduleLoop > scheduling)
  assert.doesNotMatch(installer.slice(scheduling, schedules), /await setSchedule\(tokens\[worker\]/)
})

test("installer synchronizes a changed Migration Orchestrator URL before enabling dispatch", () => {
  assert.match(installer, /previousRuntime\.migration\.orchestratorUrl !== state\.workers\.migration\.url/)
  assert.match(installer, /workerSettings\.secretSyncStatus !== "ready"/)
  assert.match(installer, /workerSettings\.synchronizedServerUrl === state\.workers\.migration\.url/)
  assert.match(installer, /workerSettings\.synchronizedSecretHash === createHash\("sha256"\)/)
  assert.match(installer, /state\.step = "github_worker_secrets_syncing"/)
  assert.match(installer, /serverUrl: state\.workers\.migration\.url \|\| ""/)
})

test("tokens are encrypted at rest, redacted by default and API is superadmin protected", () => {
  assert.match(installer, /aes-256-gcm/)
  assert.match(installer, /encryptedTokens/)
  assert.match(installer, /function primaryEncryptionKey\(\)/)
  assert.match(installer, /async function rotateSavedTokenEncryption/)
  assert.match(installer, /function postgresEncryptionMaterial\(\)/)
  assert.match(installer, /Configure PostgreSQL before securely saving Cloudflare tokens/)
  assert.doesNotMatch(installer, /Configure CLOUDFLARE_TOKEN_ENCRYPTION_KEY or AUTH_SECRET/)
  assert.doesNotMatch(installer, /SUPABASE_(?:SERVICE_ROLE_KEY|SECRET_KEY|SERVICE_KEY)/)
  assert.match(installer, /process\.env\.POSTGRES_URL/)
  assert.doesNotMatch(installer.slice(installer.indexOf("function primaryEncryptionKey"), installer.indexOf("function encryptionKeys")), /SUPABASE/)
  assert.match(installer, /const \{ encryptedTokens, \.\.\.safe \} = state/)
  assert.match(installer, /revealCloudflareTokens/)
  assert.match(route, /requireSuperAdmin\(\)/)
  assert.match(route, /mode === "separate"/)
})

test("installer is resumable, locked and keeps secrets on release redeploy", () => {
  assert.match(installer, /withDbAdvisoryLock\("cloudflare-worker-install", "singleton"/)
  assert.match(db, /pg_try_advisory_xact_lock/)
  assert.doesNotMatch(db, /pg_try_advisory_lock\(/)
  assert.match(installer, /\{ wait: false \}/)
  const reconciliation = installer.slice(installer.indexOf("export async function reconcileCloudflareWorker("), installer.indexOf("export async function reconcileCloudflareWorkers("))
  assert.match(reconciliation, /withDbAdvisoryLock\("cloudflare-worker-install", "singleton"/)
  assert.match(route, /DRIVE_ADVISORY_LOCK_BUSY/)
  assert.match(installer, /if \(input\.forceRedeploy \|\| !current\.deployed \|\| !current\.verified \|\| !artifactMatches\)/)
  assert.match(installer, /state\.secrets = previous\.secrets/)
  assert.match(installer, /status = "failed"/)
  assert.match(installer, /for \(let attempt = 0; attempt < 5/)
  assert.match(installer, /drive-file-scanner-\$\{suffix\}/)
  assert.match(installer, /setCloudflareHostingMode/)
  assert.match(installer, /installation\?\.status === "ready"/)
  assert.match(installer, /reconcileCloudflareWorkers/)
  assert.match(installer, /scriptExists/)
  assert.match(installer, /await Promise\.all\(ORDER\.map/)
  assert.match(installer, /const previousRuntime = await currentRuntimeSnapshot\(\)/)
  assert.match(installer, /for \(let attempt = 0; attempt < 3; attempt \+= 1\) \{[\s\S]*await writeRuntimeSnapshot\(previousRuntime\)/)
  assert.match(installer, /previous runtime settings could not be restored/)
  assert.match(installer, /githubSecretsSynchronized[\s\S]*previousRuntime\.migration\.orchestratorUrl[\s\S]*syncAllGitHubWorkerSecretsWithinInstallerLock/)
  assert.match(installer, /syncAllGitHubWorkerSecretsWithinInstallerLock/)
  assert.match(db, /timeout exceeded when trying to connect/)
  assert.match(installer, /current\.deployed = false; current\.verified = false/)
  assert.match(hosting, /!installationReady \? <Button/)
  assert.match(hosting, /repairAttempted/)
  assert.match(hosting, /installation\?\.status !== "failed" && installation\?\.status !== "running"/)
  assert.match(installer, /abandonedRunning/)
  assert.match(installer, /const postgresUrl = String\(process\.env\.POSTGRES_URL \|\| ""\)\.trim\(\)/)
  assert.match(installer, /current\.releaseVersion === manifest\.version/)
  assert.match(installer, /current\.artifactSha256 === artifactEntry\.sha256\.toLowerCase\(\)/)
  assert.match(installer, /state\.workers\[worker\]\.releaseVersion = manifest\.version/)
  assert.match(installer, /checkForUpdates\?: boolean/)
  assert.match(installer, /forceRedeploy\?: boolean/)
  assert.match(installer, /input\.forceRedeploy \|\| !current\.deployed \|\| !current\.verified \|\| !artifactMatches/)
  assert.match(installer, /!input\.checkForUpdates/)
  assert.match(route, /checkForUpdates: body\.checkForUpdates === true/)
  assert.match(route, /forceRedeploy: body\.forceRedeploy === true/)
  assert.match(hosting, /deploy\(false, true\)/)
  assert.match(hosting, /Check for updates/)
  assert.match(hosting, /deploy\(false, false, true\)/)
  assert.match(hosting, /Redeploy all Workers/)
  assert.doesNotMatch(hosting, /setInterval/)
  assert.match(installer, /cloudflareInstallationReady/)
  assert.match(installer, /current\.deployedAt = checkedAt; current\.verifiedAt = checkedAt/)
  assert.match(hosting, /current\.deployedAt && current\.verifiedAt && current\.lastCheckedAt/)
  assert.match(installer, /never-finished installation must be resumed by the installer/)
  assert.match(hosting, /Account details will appear only after deployment/)
  assert.match(installer, /Array\.isArray\(result\?\.schedules\)/)
  assert.match(installer, /consumers\.find\(\(consumer\) => consumer\.script_name === scriptName\) \|\| consumers\[0\]/)
})

test("fresh Worker script names migrate their Drive cron trigger within Free-plan capacity", () => {
  assert.match(installer, /async function ensureSchedule\(token: string, accountId: string, scriptName: string, replacedScriptName\?: string\)/)
  assert.match(installer, /isCronTriggerLimitError\(error\)/)
  assert.match(installer, /previousSchedules\.filter\(\(schedule\) => schedule\.cron !== "\* \* \* \* \*"\)/)
  assert.match(installer, /await replaceWorkerSchedules\(token, accountId, previousScript, previousSchedules\)\.catch\(\(\) => undefined\)/)
  assert.match(installer, /previousWorker\?\.accountId === accounts\[worker\]\.id \? previousWorker\.scriptName : undefined/)
})

test("cron exhaustion fails with actionable safe guidance and never removes unrelated triggers", () => {
  assert.match(installer, /Cloudflare account cron capacity is full \(Workers Free allows five triggers per account\)/)
  assert.match(installer, /unrelated triggers were left untouched/)
})

test("release artifacts are immutable checksummed bundles", () => {
  assert.match(installer, /checksum mismatch/)
  assert.match(installer, /release_artifacts_fetching/)
  assert.match(installer, /Promise\.all\(ORDER\.map\(async \(worker\) => \[worker, await artifact\(manifest\.workers\[worker\]\)\]\)\)/)
  assert.match(installer, /}, 6, true\)/)
  assert.match(workflow, /build-worker-release\.mjs/)
  assert.match(workflow, /gh release create .*--draft/)
  const bundleUpload = workflow.indexOf("worker-release/backend-orchestrator.mjs")
  const manifestUpload = workflow.indexOf("worker-release/manifest.json")
  const publish = workflow.indexOf("--draft=false --latest")
  assert.ok(bundleUpload > 0 && bundleUpload < manifestUpload && manifestUpload < publish)
  assert.match(workflow, /branches:\s*\n\s*- main/)
  assert.match(workflow, /workers-\$\{GITHUB_SHA:0:12\}/)
  assert.match(workflow, /--latest/)
})

test("Cloudflare hosting is presented on Workers and hidden from Settings", () => {
  assert.match(workersPage, /<CloudflareWorkerHosting \/>/)
  assert.match(settingsPage, /<Card className="hidden" aria-hidden="true">/)
  assert.match(settingsPage, /<div className="hidden" aria-hidden="true">/)
  assert.match(hosting, /Automatic hosting/)
  assert.doesNotMatch(hosting, /value="manual">Manual/)
  assert.doesNotMatch(hosting, /Manual mode uses only the URL and shared secret you provide/)
  assert.match(hosting, /Delete deployed Workers/)
  assert.match(hosting, /reconcile_worker/)
  assert.match(installer, /deleteCloudflareWorkers/)
})
