const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

const read = (path) => fs.readFileSync(path, 'utf8')

test('the orchestrator creates scan work while scanner cron and queue continue durable tasks', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  const config = read('workers/file-scanner/wrangler.jsonc')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(config, /"crons":\s*\["\* \* \* \* \*"\]/)
  assert.match(scanner, /async scheduled\(_event: ScheduledEvent, env: Env, ctx: ExecutionContext\)[\s\S]*?cycleAndContinue\(env\)/)
  assert.match(orchestrator, /async function wakeFileScanner\(db: Client\)[\s\S]*?\/run/)
  assert.match(scanner, /url\.pathname === "\/run" && request\.method === "POST"[\s\S]*?cycleAndContinue\(env\)/)
  assert.doesNotMatch(scanner, /url\.pathname === "\/status" && request\.method === "GET"[^\n]*cycle/)
  assert.match(scanner, /let schemaReady: Promise<void> \| null = null/)
})

test('scanner cron and queue drain up to four separately leased tasks concurrently', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  const config = read('workers/file-scanner/wrangler.jsonc')
  const cycle = scanner.slice(scanner.indexOf('async function cycle('), scanner.indexOf('async function cycleAndContinue'))
  assert.match(config, /"triggers":\s*\{\s*"crons":\s*\["\* \* \* \* \*"\]/)
  assert.match(scanner, /const SCAN_CONCURRENCY = 4/)
  assert.match(cycle, /for \(let slot = 0; slot < SCAN_CONCURRENCY; slot \+= 1\)/)
  assert.match(cycle, /const kinds = slot % 2 === 0 \? \["generic", "migration"\] as const : \["migration", "generic"\] as const/)
  assert.match(cycle, /for \(const kind of kinds\)[\s\S]*?claimGenericScan\(db, owner\)[\s\S]*?claim\(db, owner\)/)
  assert.match(cycle, /Promise\.all\(claimed\.tasks\.map\(async \(\{ kind, task \}\) => \{[\s\S]*?return await databaseTaskWithRetry\(env/)
  assert.match(scanner, /lease_owner=\$1,lease_expires_at=now\(\)\+interval '90 seconds'/)
  assert.match(scanner, /where migration_item_id=\$2::uuid and generation=\$3::int and lease_owner=\$4::text[\s\S]*?for update/)
  assert.match(scanner, /s\.status='pending'[\s\S]*?s\.status='running'[\s\S]*?for update of s skip locked limit 1/)
  assert.match(scanner, /make_interval\(mins=>least\(30,power\(2,least\(s\.attempt_count,5\)\)::int\)\)/)
})

test('failed concurrent scans use queue backoff instead of immediate continuation loops', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  const continuation = scanner.slice(scanner.indexOf('async function cycleAndContinue'), scanner.indexOf('export default'))
  const queue = scanner.slice(scanner.indexOf('async queue(batch:'), scanner.indexOf('async scheduled('))
  assert.match(continuation, /const failed = "ok" in result && result\.ok === false/)
  assert.match(continuation, /if \(!idle && !skipped && !failed\).*FILE_SCAN_QUEUE\.send/)
  assert.match(queue, /if \("ok" in result && result\.ok === false\) throw new Error/)
  assert.match(queue, /message\.retry\(\{ delaySeconds: Math\.min\(15 \* \(2 \*\* Math\.min\(message\.attempts, 8\)\), 900\) \}\)/)
})

test('transient scanner failures retry without an attempt ceiling and keep the durable scan cursor', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  assert.match(scanner, /client has encountered a connection error\|not queryable/)
  assert.match(scanner, /async function databaseTaskWithRetry<T>/)
  assert.match(scanner, /fresh client is required after a dropped PostgreSQL connection/)
  assert.match(scanner, /return await database\(env, operation\)/)
  assert.match(scanner, /DATABASE_RETRY_DELAYS_MS = \[250, 1_000, 3_000\]/)
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(scanner, /function isTransientScanError/)
  assert.match(scanner, /status=case when \$4::boolean then 'pending' else 'failed' end,attempt_count=attempt_count\+1/)
  assert.match(scanner, /status=case when \$5::boolean then 'pending' else 'failed' end,attempt_count=attempt_count\+1/)
  assert.doesNotMatch(scanner, /attempt_count\s*>=\s*4/)
  assert.match(orchestrator, /m\.status='failed'[\s\S]*?s\.error ~\*/)
  assert.match(orchestrator, /Resuming durable migration state/)
  assert.match(orchestrator, /Transient File Scanner error; retry[\s\S]*?saved cursor/)
})

test('Super Slurper no-overwrite progress counts skipped existing objects and only finalizes them after clean verification', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /const alreadyPresent = opts\(migration\)\.overwrite === false \? Math\.min\(objects, skipped\) : 0/)
  assert.match(orchestrator, /transferredObjects: countedTransferred, copiedObjects:/)
  assert.match(orchestrator, /alreadyPresentObjects: alreadyPresent/)
  assert.match(orchestrator, /if \(opts\(migration\)\.executionMode !== "migration_workers" && opts\(migration\)\.overwrite === false\)[\s\S]*?v\.missing_objects=0 and v\.mismatched_objects=0/)
})

test('scanner page commits are atomic, idempotent, and avoid per-page database round-trips', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  const persist = scanner.slice(scanner.indexOf('async function persistMigrationPage'), scanner.indexOf('async function compare('))
  const generic = scanner.slice(scanner.indexOf('async function processGenericScan'), scanner.indexOf('async function finishState'))
  assert.match(scanner, /function pageSize\(_env: Env\) \{ return 1000 \}/)
  assert.match(persist, /object_delta/)
  assert.match(persist, /byte_delta/)
  assert.match(persist, /on conflict\(scan_id,key\) do update/)
  assert.match(persist, /from drive_migration_verification_state[\s\S]*?for update/)
  assert.match(persist, /greatest\(0,coalesce\(s\.objects,0\)\+d\.object_delta\)/)
  assert.match(persist, /status=case when \$6::boolean then 'running' else 'completed' end,[\s\S]*?error=null/)
  assert.match(persist, /greatest\(0,coalesce\(v\.\$\{objectsColumn\},0\)\+d\.object_delta\)/)
  assert.match(persist, /begin[\s\S]*?commit[\s\S]*?rollback/)
  assert.doesNotMatch(persist, /select count\(\*\).*drive_bucket_scan_objects/i)
  assert.match(generic, /with lease as \([\s\S]*?for update[\s\S]*?incoming as \([\s\S]*?delta as \([\s\S]*?upserted as \([\s\S]*?saved_scan as \([\s\S]*?saved_item as \(/)
  assert.match(generic, /jsonb_to_recordset\(\$6::jsonb\)/)
  assert.match(generic, /on conflict\(scan_id,key\) do update/)
  assert.match(generic, /error=null,attempt_count=0,lease_owner=null,lease_expires_at=null/)
  assert.match(generic, /'sourceScanId',s\.id::text/)
  assert.match(generic, /'sourceScanStatus',case when s\.status='completed' then 'completed' else 'running' end/)
  assert.match(generic, /greatest\(0,coalesce\(s\.objects,0\)\+d\.object_delta\)/)
  assert.match(generic, /greatest\(0,coalesce\(s\.bytes,0\)\+d\.byte_delta\)/)
  assert.doesNotMatch(generic, /await pageDelta|await storePage/)
  assert.doesNotMatch(generic, /select count\(\*\).*drive_bucket_scan_objects/i)
})

test('pre-existing worker-pool objects count as completed, retain total counts, and are independently SHA-256 verified', () => {
  const worker = read('workers/migration-worker/migration-worker.mjs')
  const scanner = read('workers/file-scanner/src/index.ts')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(worker, /alreadyPresent = Math\.max\(0, sourceObjects\.length - toRepair\.length\)/)
  assert.match(worker, /integrityProofs: assignedInventory \? finalDestinationObjects\.map/)
  assert.match(worker, /integrityVerified: sourceSha256 === destinationSha256/)
  assert.match(scanner, /where s\.scan_id=\$2::uuid and not s\.is_dir_marker/)
  assert.match(scanner, /j\.result->'items'->0->'integrityProofs'->0->>'sha256' ~ '\^\[0-9a-f\]\{64\}\$'/)
  assert.match(orchestrator, /'transferredObjects',least\(coalesce\(i\.source_objects,0\)/)
  assert.match(orchestrator, /'alreadyPresentObjects',coalesce\(a\.already_present_objects,0\)/)
  assert.match(orchestrator, /'copiedObjects',coalesce\(a\.transferred_objects,0\)/)
  assert.match(orchestrator, /j\.status='completed' and case when coalesce\(j\.result->'items'->0->>'transferred'/)
})

test('retention preserves scanner inventory and verification rows while their migration is active', () => {
  const appMaintenance = read('src/lib/database-maintenance.ts')
  const worker = read('workers/backend-orchestrator/src/index.ts')
  for (const source of [appMaintenance, worker]) {
    assert.match(source, /drive_bucket_scans s join drive_migrations m on m\.id=s\.migration_id[\s\S]*?m\.status in\s*\(?\s*'running','verifying'/)
    assert.match(source, /drive_migration_items i join drive_migrations m on m\.id=i\.migration_id[\s\S]*?m\.status in\s*\(?\s*'running','verifying'/)
    assert.match(source, /drive_migrations m where m\.id=drive_bucket_scans\.migration_id[\s\S]*?m\.status in\s*\(?\s*'running','verifying'/)
  }
})

test('scanner completion wakes the Migration Orchestrator asynchronously', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  const wake = scanner.slice(scanner.indexOf('async function wakeMigrationOrchestrator'), scanner.indexOf('async function compareAndWake'))
  assert.match(wake, /\/wake/)
  assert.doesNotMatch(wake, /\/run/)
})

test('empty migrations complete in the orchestrator without requiring scanner or Slurper work', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const emptyWorkerPath = orchestrator.slice(orchestrator.indexOf('async function ensureShards'), orchestrator.indexOf('let inventoryPending'))
  const cycle = orchestrator.slice(orchestrator.indexOf('async function cycle('), orchestrator.indexOf('export default'))
  assert.match(emptyWorkerPath, /if \(!hasItems\.rowCount\)[\s\S]*?noItems: true/)
  assert.match(cycle, /const inventory = await ensureSuperSlurperInventory\(db, migration\)[\s\S]*?if \(inventory\.total === 0\)[\s\S]*?activateTargetAndCompleteMigration/)
  assert.match(cycle, /if \(shards\.noItems\)[\s\S]*?activateTargetAndCompleteMigration/)
  assert.doesNotMatch(emptyWorkerPath, /ensureWorkerTargetBuckets\(db, migration, generation\)[\s\S]*?if \(!hasItems\.rowCount\)/)
})

test('empty and verified migrations share the existing target activation and completion transaction', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const activation = orchestrator.slice(orchestrator.indexOf('async function activateTargetAndCompleteMigration'), orchestrator.indexOf('async function finishOrRepair'))
  assert.match(activation, /status=case when a\.id=\$1 then 'active' when a\.status='active' then 'available'/)
  assert.match(activation, /status='completed',completed_at=now\(\),sync_status='synced'/)
  assert.match(activation, /summary_item_count=\(select count\(\*\) from drive_migration_items/)
  assert.match(activation, /await wakeBackendOrchestrator\(db\)/)
})

test('Migration Orchestrator owns Super Slurper job creation', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const creation = orchestrator.slice(orchestrator.indexOf('async function createSuperSlurperJobs'), orchestrator.indexOf('async function syncNextBucketSettings'))
  const cycle = orchestrator.slice(orchestrator.indexOf('async function cycle('), orchestrator.indexOf('export default'))
  assert.match(creation, /cloudflare\(target, "\/slurper\/jobs", "POST"/)
  assert.match(cycle, /const jobs = await createSuperSlurperJobs\(db, migration\)/)
})
