const test = process.getBuiltinModule('node:test')
const assert = process.getBuiltinModule('node:assert/strict')
const fs = process.getBuiltinModule('node:fs')

const read = (file) => fs.readFileSync(file, 'utf8')

test('worker pool claims are generation-scoped and can signal clean completion', () => {
  const claimRoute = read('src/app/api/agents/[id]/claim-job/route.ts')
  const queue = read('src/lib/repair-jobs-store.ts')
  const runtime = read('workers/migration-worker/migration-worker.mjs')

  assert.match(claimRoute, /body\.pool === true/)
  assert.match(claimRoute, /getMigrationWorkerPoolState/)
  assert.match(claimRoute, /poolComplete: true/)
  assert.match(queue, /generation:\$\{poolCoordinates\.generation\}:inventory:%/)
  assert.match(queue, /all_migration_files_completed/)
  assert.match(queue, /migration_file_jobs_terminal/)
  assert.match(runtime, /claimed\?\.poolComplete === true/)
  assert.match(runtime, /DEFAULT_EXIT_AFTER_JOB = POOL_MODE \? "false"/)
  assert.match(runtime, /payload\.migration\?\.options\?\.overwrite !== false/)
  assert.match(runtime, /reason: "overwrite_disabled"/)
})

test('a completed GitHub pool file releases the run link for the next file', () => {
  const jobsRoute = read('src/app/api/agents/[id]/jobs/[jobId]/route.ts')
  assert.match(jobsRoute, /job\.payload\?\.kind === "migration_inventory_file"/)
  assert.match(jobsRoute, /jobReference: null/)
  assert.match(jobsRoute, /summary: `Migration file/)
  assert.match(jobsRoute, /keepPoolRunAlive\s*\?\s*"online"/)
})

test('the GitHub workflow exposes no manual dispatch fields and receives system context', () => {
  const workflow = read('.github/workflows/migration-worker.yml')
  assert.doesNotMatch(workflow, /workflow_dispatch:/)
  assert.match(workflow, /repository_dispatch:/)
  assert.match(workflow, /DRIVE_REPAIR_JOB_ID: \$\{\{ github\.event\.client_payload\.repair_job_id \|\| '' \}\}/)
  assert.match(workflow, /POSTGRES_URL: \$\{\{ secrets\.POSTGRES_URL \}\}/)
  assert.match(workflow, /POSTGRES_SSL: \$\{\{ secrets\.POSTGRES_SSL \|\| 'true' \}\}/)
  assert.doesNotMatch(workflow, /DRIVE_REPAIR_JOB_ID:.*vars\.DRIVE_REPAIR_JOB_ID/)
})

test('worker-pool details hydrate and refresh from PostgreSQL only', () => {
  const route = read('src/app/api/migrations/[id]/worker-pool/route.ts')
  const page = read('src/app/dashboard/migrations/[id]/worker-pool/page.tsx')
  assert.equal((route.match(/payload->>'migrationId'=\(\$1::uuid\)::text/g) || []).length, 1)
  assert.doesNotMatch(route, /payload->>'migrationId'=\$1\b/)
  assert.match(route, /ensureDriveSchema\(\)/)
  assert.match(route, /limit 100/)
  assert.match(route, /limit 25/)
  assert.match(route, /jsonb_array_elements/)
  assert.match(route, /fallback_needed as materialized/)
  assert.match(route, /and \(select needs_legacy from fallback_needed\)/)
  assert.match(route, /drive_migration_worker_live_state/)
  assert.equal((route.match(/await queryDb</g) || []).length, 1)
  assert.doesNotMatch(route, /listRepairJobsByMigration|listMigrationItems/)
  assert.doesNotMatch(route, /getMigrationOrchestratorSettings|fetch\(/)
  assert.match(route, /source: "database"/)
  assert.match(route, /catch \(error\)[\s\S]*?status: 500/)
  assert.match(page, /load\(false, true\),\s*active \? 5000 : 20000/)
  assert.doesNotMatch(page, /\?live=1/)
})

test('canceled migration and bucket states cannot be masked by stale verifying snapshots', () => {
  const bucketState = read('src/lib/migration-bucket-state.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const cancelRoute = read('src/app/api/migrations/[id]/action/route.ts')
  const itemRoute = read('src/app/api/migrations/[id]/items/[itemId]/action/route.ts')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(bucketState, /isAbortedStatus\(durableItemStatus\)[\s\S]*?stableLive\.status/)
  assert.match(bucketState, /if \(isAbortedStatus\(item\.slurperStatus\)\) return item\.slurperStatus/)
  assert.match(details, /\["completed", "failed", "verification_failed", "canceled"\]\.includes\(migration\.status\)/)
  assert.match(details, /migration\.status === "completed" \? formatDate\(migration\.completedAt\) : "-"/)
  assert.match(cancelRoute, /status: "canceled",\s*completedAt: null,\s*syncStatus: "syncing",\s*syncMessage: "Cancellation requested"/)
  assert.match(cancelRoute, /abortedProgress\(item, "aborted_all"/)
  assert.match(itemRoute, /migration\.status === "canceled"[\s\S]*?status: 409/)
  assert.match(orchestrator, /select id from drive_migrations where id=\$1 and status in\('running','verifying'\) for update/)
  assert.match(orchestrator, /where id=\$1 and status in\('running','verifying'\)/)
})

test('migration dashboards do not run worker sync on a timer', () => {
  const listPage = read('src/app/dashboard/migrations/page.tsx')
  const detailPage = read('src/app/dashboard/migrations/[id]/page.tsx')
  const startRoute = read('src/app/api/migrations/[id]/start/route.ts')
  assert.doesNotMatch(listPage, /setInterval\(\(\) => void tick\(\),\s*5_000\)/)
  assert.doesNotMatch(detailPage, /ACTIVE_SYNC_INTERVAL_MS|MIN_SYNC_GAP_MS/)
  assert.doesNotMatch(listPage, /\/api\/migrations\/\$\{encodeURIComponent\([^)]*\)\}\/sync/)
  assert.doesNotMatch(detailPage, /\/api\/migrations\/\$\{encodeURIComponent\([^)]*\)\}\/sync/)
  assert.match(startRoute, /\/wake/)
  assert.doesNotMatch(startRoute, /\/run`/)
})

test('reusable data-table column headers use the compact centered height', () => {
  const table = read('src/components/dashboard/data-table.tsx')
  assert.match(table, /TableRow key=\{headerGroup\.id\} className="h-8 border-b"/)
  assert.match(table, /min-h-8 w-full items-center justify-center/)
  assert.doesNotMatch(table, /min-h-9|className="h-9 border-b"/)
})

test('migration worker requires PostgreSQL and honors the configured SSL switch', () => {
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  const workerPackage = read('workers/migration-worker/package.json')
  assert.match(runtime, /if \(!POSTGRES_URL \|\| !SERVER_URL \|\| AGENT_TOKEN\.length < 24\)/)
  assert.match(runtime, /const POSTGRES_URL = String\(process\.env\.POSTGRES_URL \|\| ""\)\.trim\(\)/)
  assert.match(runtime, /POSTGRES_SSL === "false"/)
  assert.match(runtime, /const sslMode = new URL\(POSTGRES_URL\)\.searchParams\.get\("sslmode"\)/)
  assert.match(runtime, /sslMode === "disable"/)
  assert.match(runtime, /if \(currentMigrationId && Array\.isArray\(body\.items\)\)[\s\S]*?updateMigrationItemLocal\(currentMigrationId, jobId, itemUpdate\)/)
  assert.match(runtime, /update drive_migration_items set progress=\$3::jsonb/)
  assert.match(runtime, /if \(!REPAIR_JOB_ID\) return claimJobDirectPostgres\(\)/)
  assert.doesNotMatch(runtime, /supabase/i)
  assert.doesNotMatch(workerPackage, /supabase/i)
})

test('orchestrator binds the migration id as one PostgreSQL type while materializing file jobs', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /values\(gen_random_uuid\(\),\$1::uuid,'pending','migration'/)
  assert.match(orchestrator, /format\('migration:%s:generation:%s:inventory:%s:%s',\$1::uuid/)
  assert.doesNotMatch(orchestrator, /format\('migration:%s:generation:%s:inventory:%s:%s',\$1::text/)
})

test('orchestrator dispatches the fleet as soon as durable file jobs are available', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /const hasRunnableFiles = shards\.shardCount > 0 \|\| shards\.created > 0/)
  assert.match(orchestrator, /status === "running" && hasRunnableFiles \? await dispatchWorkers/)
  assert.doesNotMatch(orchestrator, /!shards\.inventoryPending && !shards\.queuePending \? await dispatchWorkers/)
})

test('orchestrator queues scanner pages incrementally without closing a running inventory', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.doesNotMatch(orchestrator, /if \(inventoryPending\) return \{ generation, shardCount: 0, created: 0, inventoryPending \}/)
  assert.match(orchestrator, /queueScan\?\.status === "completed" && page\.rowCount === 0/)
  assert.match(orchestrator, /jsonb_build_object\('status',s\.status,'objects',s\.objects,'bytes',s\.bytes/)
  assert.match(orchestrator, /temporarily empty running scan block another bucket/)
})

test('worker file records stay internal while workflow instances carry current work telemetry', () => {
  const workerPage = read('src/app/dashboard/workers/page.tsx')
  const workerApi = read('src/app/api/workers/route.ts')
  const repairApi = read('src/app/api/repair-jobs/route.ts')
  assert.doesNotMatch(workerPage, /Migration Worker Pool/)
  assert.match(workerPage, /currentWork/)
  assert.match(workerApi, /currentWork:/)
  assert.match(repairApi, /filter\(\(job\) => job\.mode !== "migration"\)/)
})

test('active worker migrations cannot be frozen by historical read-only markers', () => {
  const readOnly = read('src/lib/migration-read-only.ts')
  const detailsRoute = read('src/app/api/migrations/[id]/route.ts')
  const migrationsStore = read('src/lib/migrations-store.ts')
  const detailsPage = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(readOnly, /terminal && migration\.options\?\.historyReadOnlyAt/)
  assert.match(detailsRoute, /getMigrationDetailBootstrap\(id\)/)
  assert.match(migrationsStore, /migration\.options->>'executionMode'='migration_workers'/)
  assert.match(migrationsStore, /mapMigrationWorkerRun/)
  assert.match(detailsPage, /executionMode === "migration_workers"\) return/)
})

test('migration detail SSE snapshots reuse the one-query database bootstrap', () => {
  const stream = read('src/app/api/migrations/[id]/stream/route.ts')
  const migrationsStore = read('src/lib/migrations-store.ts')
  assert.match(stream, /getCachedStreamSnapshot\(id\)/)
  assert.match(stream, /getMigrationDetailBootstrap\(migrationId, \{ includeAccounts: false \}\)/)
  assert.match(stream, /STREAM_SNAPSHOT_CACHE_TTL_MS = 3_000/)
  assert.match(stream, /STREAM_SNAPSHOT_CACHE_MAX = 128/)
  assert.match(stream, /const \{ migration, items, workerRuns \} = bootstrap/)
  assert.doesNotMatch(stream, /getMigration\(|listMigrationItems\(|listMigrationWorkerRuns\(/)
  assert.match(stream, /nextDelay = \["running", "verifying", "queued"\]\.includes\(migration\.status\) \? 4_000 : 15_000/)
  const bootstrap = migrationsStore.match(/export async function getMigrationDetailBootstrap\([\s\S]*?\n}\n/)
  assert.ok(bootstrap, 'expected the consolidated migration detail bootstrap')
  assert.equal((bootstrap[0].match(/queryDb</g) ?? []).length, 1)
})

test('migration orchestrator projects durable per-file completion into live bucket counts', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /async function refreshWorkerItemProgress/)
  assert.match(orchestrator, /'transferredObjects',coalesce\(a\.completed_objects,0\)/)
  assert.match(orchestrator, /v\.status='completed' and v\.missing_objects=0 and v\.mismatched_objects=0/)
  assert.match(orchestrator, /then 'verification_failed'/)
  assert.match(orchestrator, /await refreshWorkerItemProgress\(db, migration, shards\.generation\)/)
})

test('orchestrator continuously maintains every registered workflow instance', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  assert.match(orchestrator, /where provider='github_actions' and status<>'disabled'/)
  assert.match(orchestrator, /Workflow heartbeat expired; replacement dispatched/)
  assert.match(orchestrator, /payload->>'workerInstanceId'/)
  assert.doesNotMatch(orchestrator, /const ids = Array\.isArray\(opts\(migration\)\.workerAgentIds\)/)
  assert.match(runtime, /getArg\("poll-ms", "1000"\)/)
})

test('worker job details live only below their migration route', () => {
  assert.equal(fs.existsSync('src/app/dashboard/workers/jobs/[id]/page.tsx'), false)
  assert.equal(fs.existsSync('src/app/dashboard/migrations/[id]/jobs/[jobId]/page.tsx'), true)
  const migrationDetails = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.doesNotMatch(migrationDetails, /dashboard\/workers\/jobs\//)
})

test('migration details never regress worker counters on refresh or reconnect', () => {
  const detailsPage = read('src/app/dashboard/migrations/[id]/page.tsx')
  const bucketState = read('src/lib/migration-bucket-state.ts')
  const migrationOrchestrator = read('workers/migration-orchestrator/src/index.ts')
  const backendReconciler = read('src/app/api/internal/backend-orchestrator/reconcile/route.ts')
  const itemActionRoute = read('src/app/api/migrations/[id]/items/[itemId]/action/route.ts')
  assert.match(detailsPage, /const sameWorkerGeneration =/)
  assert.match(detailsPage, /prevGeneration === nextGeneration/)
  assert.match(detailsPage, /totalObjects: Math\.max\(prevLive\.totalObjects, nextLive\.totalObjects\)/)
  assert.match(detailsPage, /transferredBytes:[\s\S]*Math\.max\(prevLive\.transferredBytes, nextLive\.transferredBytes\)/)
  assert.match(bucketState, /live\.workerStage === "migration" \|\| live\.workerStage === "verification"/)
  assert.match(migrationOrchestrator, /async function refreshSuperSlurperProgress/)
  assert.match(migrationOrchestrator, /slurper\/jobs\/\$\{encodeURIComponent\(item\.slurper_job_id\)\}\/progress/)
  assert.match(migrationOrchestrator, /drive_migration_verification_state/)
  assert.doesNotMatch(backendReconciler, /syncMigrationLiveState|listMigrations/)
  assert.doesNotMatch(detailsPage, /syncMigrationLiveState/)
  assert.match(itemActionRoute, /queueMigrationItemVerification\(id, item\.id\)/)
  assert.doesNotMatch(itemActionRoute, /runBucketScanBatch|r2ListAllObjects|r2HeadObject|createInitialBucketVerifyState/)
})

test('file scanner comparison binds UUID and text parameters explicitly', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  assert.match(scanner, /migration_item_id=\$1::uuid/)
  assert.match(scanner, /j\.payload->'itemIds'->>0=\$1::text/)
  assert.match(scanner, /j\.migration_id=\$9::uuid/)
  assert.match(scanner, /not s\.is_dir_marker/)
  assert.match(scanner, /not d\.is_dir_marker/)
})

test('worker verification can be rerun for failed buckets while migration continues', () => {
  const action = read('src/app/api/migrations/[id]/action/route.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(action, /current\.status in\('failed','completed'\)/)
  assert.match(action, /migration\.status === "running" \? "running" : "verifying"/)
  assert.match(details, /workerPoolMigration && effectiveMigrationStatus !== "completed" && \(hasVerificationFailure \|\| overviewProgress\.verifyIssues > 0\)/)
  assert.doesNotMatch(details, /workerPoolMigration && \(hasVerificationFailure \|\| allBucketsTerminal/)
})

test('verified bucket settings respect strict destination verification', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /and \(v\.extra_objects=0 or \$2=false\)/)
  assert.match(orchestrator, /add column if not exists attempt_generation integer/)
  assert.match(orchestrator, /where drive_migration_verification_state\.generation<>excluded\.generation/)
})

test('orchestrator persists bucket stage and settings events for migration logs', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(orchestrator, /async function recordItemStageEvents/)
  assert.match(orchestrator, /'File Scanner verification passed; bucket migration completed'/)
  assert.match(orchestrator, /'Bucket settings synchronized after successful verification'/)
  assert.match(orchestrator, /await recordItemStageEvents\(db, migration, shards\.generation\)/)
  assert.doesNotMatch(details, /files completed`/)
})

test('verification failure stays distinct from transfer failure and is recoverable', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const scanner = read('workers/file-scanner/src/index.ts')
  const action = read('src/app/api/migrations/[id]/items/[itemId]/action/route.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const migrations = read('src/app/dashboard/migrations/page.tsx')
  const readOnly = read('src/lib/migration-read-only.ts')

  assert.match(orchestrator, /status='verification_failed',sync_status='failed',sync_message=\$2/)
  assert.match(orchestrator, /slurper_status='verification_failed'/)
  assert.match(orchestrator, /when 'verification_failed' then coalesce\([\s\S]*missing_objects/)
  assert.match(orchestrator, /await recordItemStageEvents\(db, migration, 1\)/)
  assert.match(orchestrator, /Super Slurper transfer completed; File Scanner verification pending/)
  assert.doesNotMatch(orchestrator, /when 'completed' then 'Bucket migration completed'/)
  assert.match(scanner, /phase=\$9::text,status='pending',attempt_count=0,last_error=null/)
  assert.match(scanner, /mismatched_objects=c\.mismatched,extra_objects=c\.extra,attempt_count=0,last_error=null/)
  assert.match(action, /s === "verification_failed"/)
  assert.match(action, /slurperStatus: "verifying"/)
  assert.match(action, /Manual File Scanner verification requested/)
  assert.match(details, /normalizedDisplayStatus === "verification_failed"/)
  assert.match(details, /verificationWasExplicitlyRequeued/)
  assert.match(details, /normalizedDisplayStatus !== "verification_failed" && \(verifyStatus === "error"/)
  assert.match(details, /!\["completed", "failed", "verification_failed"\]\.includes\(String\(effectiveMigrationStatus\)\)/)
  assert.match(details, /effectiveMigrationStatus !== "verification_failed" \?/)
  assert.match(details, /rawMessage === "Bucket migration completed"[\s\S]*File Scanner verification pending/)
  assert.match(migrations, /s === "verification_failed".*Verification failed/)
  assert.match(readOnly, /"completed", "failed", "verification_failed", "canceled"/)
})

test('Super Slurper repair re-enters the shared worker-pool scan, queue, copy, and verification lifecycle', () => {
  const action = read('src/app/api/migrations/[id]/action/route.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const route = read('src/app/api/migrations/[id]/route.ts')
  const stream = read('src/app/api/migrations/[id]/stream/route.ts')
  const runtime = read('workers/migration-worker/migration-worker.mjs')

  assert.match(action, /executionMode: "migration_workers"/)
  assert.match(action, /workerGeneration: nextGeneration/)
  assert.match(action, /workerRepairMismatchedObjects: true/)
  assert.match(action, /wakeMigrationOrchestrator\(\)/)
  assert.match(action, /File Scanner must be configured and enabled/)
  assert.match(runtime, /workerRepairMismatchedObjects === true/)
  assert.match(runtime, /inspectAssignedObjects\(sourceClient, targetClient/)
  assert.match(runtime, /sourceSha256 === destinationSha256/)
  assert.match(details, /Repair with worker pool/)
  assert.doesNotMatch(details, /Run with worker|workersOpen|Worker Overview|repair_and_verify/)
  assert.doesNotMatch(route, /listRepairJobsByMigration/)
  assert.doesNotMatch(stream, /listRepairJobsByMigration/)
})

test('worker-pool repair reconciles destinations before copy and bucket preparation stays worker-owned', () => {
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const startRoute = read('src/app/api/migrations/[id]/start/route.ts')
  assert.match(startRoute, /Queued for Migration Orchestrator/)
  assert.match(startRoute, /await wakeMigrationOrchestrator\(\)/)
  assert.doesNotMatch(startRoute, /r2ListBuckets|r2CreateBucketViaApi|ensureTargetBucketExists|slurperCreateJob|slurperGetActiveJobCount/)
  assert.doesNotMatch(startRoute, /executionMode === "migration_workers"/)
  assert.match(orchestrator, /async function ensureWorkerTargetBuckets/)
  assert.match(orchestrator, /await ensureWorkerTargetBuckets\(db, migration, generation\)/)
  assert.match(runtime, /const \[sourceSha256, destinationSha256\] = await Promise\.all/)
  assert.match(runtime, /sourceSha256 === destinationSha256/)
  assert.match(runtime, /alreadyPresent = Math\.max\(0, sourceObjects\.length - toRepair\.length\)/)
  assert.match(runtime, /already verified, \$\{initialMissing\} missing/)
  assert.ok(runtime.indexOf('const [sourceSha256, destinationSha256]') < runtime.indexOf('if (isMismatch && !overwrite)'), 'destination integrity checks must run before the overwrite setting is applied')
  assert.match(runtime, /if \(!isMismatch && latestTargetSize === objectSize\)/)
  assert.match(orchestrator, /'transferredObjects',coalesce\(a\.completed_objects,0\)/)
  assert.match(orchestrator, /await ensureBucketVerification\(db, migration, shards\.generation\)/)
})
