const test = process.getBuiltinModule('node:test')
const assert = process.getBuiltinModule('node:assert/strict')
const fs = process.getBuiltinModule('node:fs')

const read = (file) => fs.readFileSync(file, 'utf8')

test('worker pool claims are generation-scoped and can signal clean completion', () => {
  const claimRoute = read('src/app/api/agents/[id]/claim-job/route.ts')
  const queue = read('src/lib/repair-jobs-store.ts')
  const runtime = read('workers/migration-worker/migration-worker.mjs')

  assert.match(claimRoute, /body\.pool === true/)
  assert.match(claimRoute, /getMigrationWorkerPoolState/)
  assert.match(claimRoute, /poolComplete: true/)
  assert.match(queue, /generation:\$\{poolCoordinates\.generation\}:inventory:%/)
  assert.match(queue, /all_migration_files_completed/)
  assert.match(queue, /migration_file_jobs_terminal/)
  assert.match(runtime, /claimed\?\.poolComplete === true/)
  assert.match(runtime, /DEFAULT_EXIT_AFTER_JOB = POOL_MODE \? "false"/)
  assert.match(runtime, /payload\.migration\?\.options\?\.overwrite !== false/)
  assert.match(runtime, /reason: "overwrite_disabled"/)
})

test('a completed GitHub pool file releases the run link for the next file', () => {
  const jobsRoute = read('src/app/api/agents/[id]/jobs/[jobId]/route.ts')
  assert.match(jobsRoute, /job\.payload\?\.kind === "migration_inventory_file"/)
  assert.match(jobsRoute, /jobReference: null/)
  assert.match(jobsRoute, /summary: `Migration file/)
  assert.match(jobsRoute, /keepPoolRunAlive\s*\?\s*"online"/)
})

test('the GitHub workflow exposes no manual dispatch fields and receives system context', () => {
  const workflow = read('.github/workflows/migration-worker.yml')
  assert.doesNotMatch(workflow, /workflow_dispatch:/)
  assert.match(workflow, /repository_dispatch:/)
  assert.match(workflow, /DRIVE_REPAIR_JOB_ID: \$\{\{ github\.event\.client_payload\.repair_job_id \|\| '' \}\}/)
  assert.doesNotMatch(workflow, /POSTGRES_URL|POSTGRES_SSL/)
  assert.match(workflow, /Validate worker configuration/)
  assert.match(workflow, /DRIVE_MIGRATION_ORCHESTRATOR_URL GitHub secret is missing/)
  assert.doesNotMatch(workflow, /DRIVE_REPAIR_JOB_ID:.*vars\.DRIVE_REPAIR_JOB_ID/)
})

test('GitHub migration workers receive only Orchestrator URL and shared worker secret', () => {
  const route = read('src/app/api/agents/[id]/dispatch/route.ts')
  const helper = read('src/lib/github-worker-secrets.ts')
  const workflow = read('.github/workflows/migration-worker.yml')
  assert.match(route, /syncGitHubWorkerSecrets/)
  assert.match(helper, /DRIVE_MIGRATION_ORCHESTRATOR_URL/)
  assert.match(helper, /DRIVE_WORKER_SHARED_SECRET/)
  assert.doesNotMatch(helper, /POSTGRES_URL|postgresUrl/)
  assert.match(workflow, /SERVER_URL: \$\{\{ secrets\.DRIVE_MIGRATION_ORCHESTRATOR_URL \}\}/)
  assert.match(workflow, /TOKEN: \$\{\{ secrets\.DRIVE_WORKER_SHARED_SECRET \}\}/)
})

test('GitHub worker configuration changes synchronize every repository without taking over dispatch', () => {
  const helper = read('src/lib/github-worker-secrets.ts')
  const workerSettings = read('src/app/api/settings/migration-workers/route.ts')
  const orchestratorSettings = read('src/app/api/settings/migration-orchestrator/route.ts')
  assert.match(helper, /export async function syncAllGitHubWorkerSecrets/)
  assert.match(helper, /REPOSITORY_SYNC_CONCURRENCY = 4/)
  assert.match(helper, /Promise\.allSettled/)
  assert.match(helper, /synchronizedServerUrl|serverUrl/)
  assert.match(helper, /createHash\("sha256"\)/)
  assert.match(workerSettings, /syncAllGitHubWorkerSecrets/)
  assert.match(orchestratorSettings, /settings\.orchestratorUrl !== current\.orchestratorUrl/)
  assert.match(orchestratorSettings, /syncAllGitHubWorkerSecrets/)
  assert.doesNotMatch(helper, /repository_dispatch|\/dispatches/)
  assert.doesNotMatch(orchestratorSettings, /repository_dispatch|\/dispatches/)
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /githubWorkerSecretsAreCurrent/)
  assert.match(orchestrator, /synchronizedServerUrl/)
  assert.match(orchestrator, /synchronizedSecretHash/)
})

test('the dashboard dispatch route cannot dispatch a GitHub workflow outside the Migration Orchestrator', () => {
  const route = read('src/app/api/agents/[id]/dispatch/route.ts')
  assert.match(route, /if \(agent\.provider === "github_actions"\)[\s\S]*Migration Orchestrator\. Start or retry this migration with the worker pool/)
  const workersPage = read('src/app/dashboard/workers/page.tsx')
  assert.doesNotMatch(workersPage, /Dispatch GitHub worker|Stop worker|stop_run|\/dispatch/)
})

test('migration-pool cancellation is an orchestrator-owned durable intent', () => {
  const route = read('src/app/api/repair-jobs/[id]/route.ts')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(route, /job\.mode === "migration"[\s\S]*?Migration Orchestrator is stopping the active worker pool/)
  assert.match(orchestrator, /reconcileCanceledWorkerRepairJobs/)
  assert.match(orchestrator, /githubAbortRequestedAt/)
  assert.match(orchestrator, /Migration worker job .* was canceled/)
  assert.match(orchestrator, /if \(stopped\.rowCount\) return 0/)
  assert.match(orchestrator, /pool_stopped/)
  assert.match(orchestrator, /secretSyncStatus[\s\S]*!== "ready"/)
})

test('orchestrator reconciles GitHub worker runs whose migration is deleted or terminal', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /async function reconcileOrphanedGitHubDispatches\(db: Client\)/)
  assert.match(orchestrator, /where r\.run_type='github_dispatch' and r\.status in\('pending','running'\)[\s\S]*?not exists\([\s\S]*?m\.status in\('running','verifying'\)/)
  assert.match(orchestrator, /githubAbortRequestedAt',coalesce\(payload->>'githubAbortRequestedAt',now\(\)::text\)/)
  assert.match(orchestrator, /await abortMigrationWorkers\(db, migrationId, `Migration \$\{migrationId\} is missing or terminal/)
  assert.match(orchestrator, /const orphanedWorkerRuns = await reconcileOrphanedGitHubDispatches\(db\)/)
  assert.match(orchestrator, /idle: true, canceledWorkerJobs, orphanedWorkerRuns/)
})

test('GitHub cancellation compares migration ids consistently as text', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const abort = orchestrator.slice(orchestrator.indexOf('async function abortMigrationWorkers'), orchestrator.indexOf('async function reconcileCanceledWorkerRepairJobs'))
  assert.match(abort, /r\.payload->>'migrationId'=\$1::text/)
  assert.match(abort, /j\.migration_id::text=\$1::text/)
  assert.match(abort, /m\.id::text=\$1::text/)
  assert.doesNotMatch(abort, /r\.payload->>'migrationId'=\$1(?!::text)/)
})

test('an explicit canceled pool attempt is not silently revived by recovery', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const recovery = orchestrator.slice(orchestrator.indexOf('async function recoverJobs'), orchestrator.indexOf('async function refreshWorkerItemProgress'))
  assert.match(recovery, /status='failed'.*retryCount/)
  assert.doesNotMatch(recovery, /or status='canceled'/)
})

test('late workers cannot claim migration files before the full inventory and queue are committed', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const claim = orchestrator.slice(orchestrator.indexOf('if (action === "claim-job")'), orchestrator.indexOf('const jobId = match[3]'))
  assert.match(claim, /inventoryReady[\s\S]*migrationInventory[\s\S]*migrationQueue[\s\S]*inventory_incomplete/)
})

test('verification scans never replace the frozen migration source inventory totals', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  assert.match(scanner, /not exists\(select 1 from drive_migration_verification_state v where v\.source_scan_id=s\.id\)/)
  const verificationComplete = scanner.slice(scanner.indexOf('), item_done as ('), scanner.indexOf(') select missing,mismatched,extra from state_done'))
  assert.doesNotMatch(verificationComplete, /source_objects=\$6|source_bytes=\$7/)
})

test('historical worker-pool tabs build bucket progress from their selected generation', () => {
  const route = read('src/app/api/migrations/[id]/worker-pool/route.ts')
  assert.match(route, /historical_bucket_projection/)
  assert.match(route, /resolvedGeneration !== currentGeneration/)
  assert.match(route, /historical_buckets/)
})

test('worker-pool details hydrate and refresh from PostgreSQL only', () => {
  const route = read('src/app/api/migrations/[id]/worker-pool/route.ts')
  const page = read('src/app/dashboard/migrations/[id]/worker-pool/page.tsx')
  assert.ok((route.match(/payload->>'migrationId'=\(\$1::uuid\)::text/g) || []).length >= 1)
  assert.doesNotMatch(route, /payload->>'migrationId'=\$1\b/)
  assert.match(route, /ensureDriveSchema\(\)/)
  assert.match(route, /limit 100/)
  assert.match(route, /limit 25/)
  assert.match(route, /jsonb_array_elements/)
  assert.match(route, /fallback_needed as materialized/)
  assert.match(route, /and \(select needs_legacy from fallback_needed\)/)
  assert.match(route, /drive_migration_worker_live_state/)
  assert.equal((route.match(/await queryDb</g) || []).length, 1)
  assert.doesNotMatch(route, /listRepairJobsByMigration|listMigrationItems/)
  assert.doesNotMatch(route, /getMigrationOrchestratorSettings|fetch\(/)
  assert.match(route, /source: "database"/)
  assert.match(route, /catch \(error\)[\s\S]*?status: 500/)
  assert.match(page, /setInterval\(\(\) => void load\(\{ background: true \}\), 5_000\)/)
  assert.match(page, /inFlight\.current/)
  assert.match(page, /DashboardDataTable/)
  assert.match(page, /serverPagination/)
  assert.match(route, /attempt_generations as materialized/)
  assert.match(route, /selected_worker_runs as/)
  assert.match(route, /selected_generation/)
  assert.match(page, /Worker-pool attempts/)
  assert.match(page, /Dispatched workers/)
  assert.match(page, /File queue/)
  assert.doesNotMatch(page, /\?live=1/)
})

test('migration worker cards prefer running workflows and terminal parents over stale deployment state', () => {
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const poolRoute = read('src/app/api/migrations/[id]/worker-pool/route.ts')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(details, /const runningRuns = currentRuns\.filter/)
  assert.match(details, /runningRuns\.length > 0\s*\? "running"/)
  assert.match(details, /run\.online \|\| \(String\(run\.status\).*?=== "pending" && !run\.abortRequested\)/s)
  assert.match(details, /displayStatus: "aborted", queued: 0/)
  assert.match(poolRoute, /status: "aborted", queuedObjects: 0/)
  assert.match(orchestrator, /active\.status in\('running','verifying'\)/)
})

test('canceled migration and bucket states cannot be masked by stale verifying snapshots', () => {
  const bucketState = read('src/lib/migration-bucket-state.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const cancelRoute = read('src/app/api/migrations/[id]/action/route.ts')
  const itemRoute = read('src/app/api/migrations/[id]/items/[itemId]/action/route.ts')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const cancelAction = cancelRoute.slice(cancelRoute.indexOf('if (action === "cancel_migration") {'), cancelRoute.indexOf('if (action === "settings_sync")'))
  assert.match(bucketState, /isAbortedStatus\(durableItemStatus\)[\s\S]*?stableLive\.status/)
  assert.match(bucketState, /if \(isAbortedStatus\(item\.slurperStatus\)\) return item\.slurperStatus/)
  assert.match(details, /\["completed", "failed", "verification_failed", "canceled"\]\.includes\(migration\.status\)/)
  assert.match(details, /migration\.status === "completed" \? formatDate\(migration\.completedAt\) : "-"/)
  assert.match(cancelRoute, /status: "canceled",\s*completedAt: null,\s*syncStatus: "syncing",\s*syncMessage: "Cancellation requested"/)
  assert.match(cancelRoute, /abortedProgress\(item, "aborted_all"/)
  assert.match(cancelAction, /const workerMode = migration\.options\.executionMode === "migration_workers"[\s\S]*?if \(workerMode\)[\s\S]*?await wakeMigrationOrchestrator\(\)/)
  assert.match(cancelRoute, /function cancelActiveMigrationFileJobs[\s\S]*?with canceled as \([\s\S]*?update drive_repair_jobs[\s\S]*?where migration_id=\$1 and status in\('pending','claimed','running'\)/)
  assert.doesNotMatch(cancelRoute, /abortGitHubDispatchesForMigration|listGitHubWorkflowRuns/)
  assert.match(cancelAction, /GitHub dispatch and cancellation belong to the orchestrator/)
  assert.doesNotMatch(cancelRoute, /if \(action === "cancel_migration" && migration\.status === "canceled"\)\s*\{\s*return NextResponse\.json\(\{ ok: true, alreadyCanceled: true/)
  assert.match(cancelRoute, /readOnly\.readOnly && !workerMaintenanceAction && action !== "cancel_migration"/)
  assert.match(itemRoute, /migration\.status === "canceled"[\s\S]*?status: 409/)
  assert.match(orchestrator, /select id from drive_migrations where id=\$1 and status in\('running','verifying'\) for update/)
  assert.match(orchestrator, /where id=\$1 and status in\('running','verifying'\)/)
  assert.match(orchestrator, /const terminalStatus = \["cancelled", "canceled", "cancelled_by_user"\][\s\S]*?status=\$2,summary=\$3,completed_at=now\(\),external_run_id=\$4/)
})

test('migration pool abort and job deletion preserve orchestrator ownership and stopping guards', () => {
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const jobPage = read('src/app/dashboard/migrations/[id]/jobs/[jobId]/page.tsx')
  const poolPage = read('src/app/dashboard/migrations/[id]/worker-pool/page.tsx')
  const jobsRoute = read('src/app/api/repair-jobs/[id]/route.ts')
  assert.match(details, /canAbortPool[\s\S]*?runMigrationAction\("cancel_migration"\)[\s\S]*?Details/)
  assert.match(jobPage, /redirect\(`\/dashboard\/migrations\/\$\{encodeURIComponent\(id\)\}\/worker-pool`\)/)
  assert.match(poolPage, /onClick=\{\(\) => setDeleteOpen\(true\)\}/)
  assert.match(poolPage, /method: "POST" \| "DELETE"/)
  assert.match(poolPage, /Active jobs must be aborted and fully stopped first/)
  assert.match(jobsRoute, /job\.mode === "migration"[\s\S]*?r\.status in\('pending','running'\)[\s\S]*?status: 409/)
  assert.match(jobsRoute, /Abort this worker job and wait for the Migration Orchestrator/)
  assert.match(jobsRoute, /active migration's stop marker/)
})

test('migration dashboards do not run worker sync on a timer', () => {
  const listPage = read('src/app/dashboard/migrations/page.tsx')
  const detailPage = read('src/app/dashboard/migrations/[id]/page.tsx')
  const startRoute = read('src/app/api/migrations/[id]/start/route.ts')
  assert.doesNotMatch(listPage, /setInterval\(\(\) => void tick\(\),\s*5_000\)/)
  assert.doesNotMatch(detailPage, /ACTIVE_SYNC_INTERVAL_MS|MIN_SYNC_GAP_MS/)
  assert.doesNotMatch(listPage, /\/api\/migrations\/\$\{encodeURIComponent\([^)]*\)\}\/sync/)
  assert.doesNotMatch(detailPage, /\/api\/migrations\/\$\{encodeURIComponent\([^)]*\)\}\/sync/)
  assert.match(startRoute, /\/wake/)
  assert.doesNotMatch(startRoute, /\/run`/)
})

test('reusable data-table column headers use the compact centered height', () => {
  const table = read('src/components/dashboard/data-table.tsx')
  assert.match(table, /TableRow key=\{headerGroup\.id\} className="h-8 border-b"/)
  assert.match(table, /min-h-8 w-full items-center justify-center/)
  assert.doesNotMatch(table, /min-h-9|className="h-9 border-b"/)
})

test('migration worker uses the Orchestrator and never opens a direct PostgreSQL connection', () => {
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  const workerPackage = read('workers/migration-worker/package.json')
  assert.match(runtime, /SERVER_URL and the common Migration Worker secret are required/)
  assert.match(runtime, /\/workers\/\$\{encodeURIComponent\(AGENT_ID\)\}\/claim-job/)
  assert.match(runtime, /\/workers\/\$\{encodeURIComponent\(AGENT_ID\)\}\/heartbeat/)
  assert.doesNotMatch(runtime, /POSTGRES_URL|POSTGRES_SSL|from "pg"|postgres\(/)
  assert.match(workerPackage, /"@aws-sdk\/client-s3"/)
  assert.doesNotMatch(workerPackage, /"pg"/)
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /currentJobId && claimToken[\s\S]*?set last_heartbeat_at=now\(\)/)
  assert.match(orchestrator, /requestedJobId[\s\S]*?status='pending' for update skip locked/)
  assert.match(orchestrator, /Migration item phase and counters are projections/)
  assert.match(orchestrator, /await refreshWorkerItemProgress\(db, migration,[\s\S]*affectedItemIds\)/)
  assert.doesNotMatch(orchestrator, /for \(const itemUpdate of body\.items\.slice\(0, 100\)\)/)
  assert.doesNotMatch(runtime, /supabase/i)
  assert.doesNotMatch(workerPackage, /supabase/i)
})

test('orchestrator binds the migration id as one PostgreSQL type while materializing file jobs', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /select gen_random_uuid\(\),\$3::uuid,'pending','migration'/)
  assert.match(orchestrator, /format\('migration:%s:generation:%s:inventory:%s:%s',\$3::uuid/)
  assert.doesNotMatch(orchestrator, /format\('migration:%s:generation:%s:inventory:%s:%s',\$1::text/)
  assert.match(orchestrator, /with page as materialized[\s\S]*from page object_row[\s\S]*\[queueScan\?\.id, lastKey, migration\.id, generation, queueItem\.id\]/)
})

test('orchestrator dispatches the fleet only after all scanner inventory is materialized', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /const inventoryReady = !shards\.inventoryPending && !shards\.queuePending/)
  assert.match(orchestrator, /status === "running" && inventoryReady && hasRunnableFiles \? await dispatchWorkers/)
  assert.match(orchestrator, /every source inventory is complete and every scanned object/)
})

test('orchestrator queues scanner pages incrementally without closing a running inventory', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.doesNotMatch(orchestrator, /if \(inventoryPending\) return \{ generation, shardCount: 0, created: 0, inventoryPending \}/)
  assert.match(orchestrator, /queueScan\?\.status === "completed" && pageCount === 0/)
  assert.match(orchestrator, /MIN_QUEUE_BATCH_SIZE = 500/)
  assert.match(orchestrator, /DEFAULT_QUEUE_BATCH_SIZE = 2_000/)
  assert.match(orchestrator, /MAX_QUEUE_BATCH_SIZE = 4_000/)
  assert.match(orchestrator, /select exists\(select 1 from drive_bucket_scan_objects[\s\S]*?has_page/)
  assert.match(orchestrator, /materializedObjects: priorMaterialized \+ pageCount/)
  assert.doesNotMatch(orchestrator, /jsonb_to_recordset\(\$4::jsonb\)/)
  assert.match(orchestrator, /tuneQueueBatchSize/)
  assert.match(orchestrator, /count\(j\.\*\) filter\(where j\.status='pending'\)::bigint queued_objects/)
  assert.match(orchestrator, /Building migration queue for migration workers/)
  assert.match(orchestrator, /jsonb_build_object\('status',s\.status,'objects',s\.objects,'bytes',s\.bytes/)
  assert.match(orchestrator, /temporarily empty running scan block another bucket/)
})

test('worker file records stay internal while workflow instances carry current work telemetry', () => {
  const workerPage = read('src/app/dashboard/workers/page.tsx')
  const workerApi = read('src/app/api/workers/route.ts')
  const repairApi = read('src/app/api/repair-jobs/route.ts')
  assert.doesNotMatch(workerPage, /Migration Worker Pool/)
  assert.match(workerPage, /currentWork/)
  assert.match(workerApi, /currentWork:/)
  assert.match(repairApi, /filter\(\(job\) => job\.mode !== "migration"\)/)
})

test('active worker migrations cannot be frozen by historical read-only markers', () => {
  const readOnly = read('src/lib/migration-read-only.ts')
  const detailsRoute = read('src/app/api/migrations/[id]/route.ts')
  const migrationsStore = read('src/lib/migrations-store.ts')
  const detailsPage = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(readOnly, /terminal && migration\.options\?\.historyReadOnlyAt/)
  assert.match(detailsRoute, /getMigrationDetailBootstrap\(id\)/)
  assert.match(migrationsStore, /migration\.options->>'executionMode'='migration_workers'/)
  assert.match(migrationsStore, /mapMigrationWorkerRun/)
  assert.match(detailsPage, /executionMode === "migration_workers"\) return/)
})

test('migration detail SSE snapshots reuse the one-query database bootstrap', () => {
  const stream = read('src/app/api/migrations/[id]/stream/route.ts')
  const migrationsStore = read('src/lib/migrations-store.ts')
  assert.match(stream, /getCachedStreamSnapshot\(id\)/)
  assert.match(stream, /getMigrationDetailBootstrap\(migrationId, \{ includeAccounts: false \}\)/)
  assert.match(stream, /STREAM_SNAPSHOT_CACHE_TTL_MS = 3_000/)
  assert.match(stream, /STREAM_SNAPSHOT_CACHE_MAX = 128/)
  assert.match(stream, /const \{ migration, items, workerRuns \} = bootstrap/)
  assert.doesNotMatch(stream, /getMigration\(|listMigrationItems\(|listMigrationWorkerRuns\(/)
  assert.match(stream, /nextDelay = \["running", "verifying", "queued"\]\.includes\(migration\.status\) \? 4_000 : 15_000/)
  const bootstrap = migrationsStore.match(/export async function getMigrationDetailBootstrap\([\s\S]*?\n}\n/)
  assert.ok(bootstrap, 'expected the consolidated migration detail bootstrap')
  assert.equal((bootstrap[0].match(/queryDb</g) ?? []).length, 1)
})

test('migration orchestrator projects durable per-file completion into live bucket counts', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /async function refreshWorkerItemProgress/)
  assert.match(orchestrator, /'transferredObjects',least\(coalesce\(i\.source_objects,0\)/)
  assert.match(orchestrator, /a\.transferred_objects/)
  assert.match(orchestrator, /'skippedObjects',greatest\(/)
  assert.match(orchestrator, /v\.status='completed' and v\.missing_objects=0 and v\.mismatched_objects=0/)
  assert.match(orchestrator, /then 'verification_failed'/)
  assert.match(orchestrator, /await refreshWorkerItemProgress\(db, migration, shards\.generation\)/)
})

test('migration worker reports cannot flip bucket phase or race shared counters', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const report = orchestrator.slice(orchestrator.indexOf('async function workerRequest'), orchestrator.indexOf('async function cycle('))
  assert.match(report, /Migration item phase and counters are projections of the durable job/)
  assert.doesNotMatch(report, /nextLiveStatus|nextItemStatus|stage\.includes\("scan"\)|stage\.includes\("verif"\)/)
  assert.match(report, /await refreshWorkerItemProgress\(db, migration,[\s\S]*affectedItemIds\)/)
  assert.match(orchestrator, /greatest\(case when \(j\.result->'items'->0->>'transferred'\)/)
  assert.match(orchestrator, /coalesce\(i\.progress,'\{\}'::jsonb\)-'repairWorker'-'repairWorkerStatus'/)
})

test('worker-pool migration enforces scan then transfer then independent bucket verification', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const scanner = read('workers/file-scanner/src/index.ts')
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  const verifyClaim = scanner.slice(scanner.indexOf('async function claim('), scanner.indexOf('async function claimGenericScan'))
  assert.match(orchestrator, /every source inventory is complete and every scanned object/)
  assert.match(orchestrator, /scan_item\.progress->'migrationInventory'->>'status',''\)<>'completed'/)
  assert.match(orchestrator, /j\.work_key like \$3 and j\.status<>'completed'/)
  assert.match(verifyClaim, /m\.options->>'executionMode' is distinct from 'migration_workers'/)
  assert.match(verifyClaim, /j\.status<>'completed'/)
  assert.match(orchestrator, /o\.scan_id is distinct from nullif\(i\.progress->'migrationInventory'->>'sourceScanId'/)
  assert.match(orchestrator, /select i\.id,i\.migration_id,\$2,null,'pending','source'/)
  assert.match(orchestrator, /waiting_for_transfers/)
  assert.match(orchestrator, /status not in\('pending','blocked'\)/)
  assert.match(runtime, /stage = "repair_verify"/)
  assert.match(runtime, /integrityProofs/)
  assert.match(runtime, /finalizeJobUpdate\(job\.id,[\s\S]*status: completed \? "completed" : "failed"/)
})

test('pool workflow roster is reread on every orchestrator cycle and newly configured workflows get capacity', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const dispatch = orchestrator.slice(orchestrator.indexOf('async function dispatchWorkers'), orchestrator.indexOf('async function abortMigrationWorkers'))
  assert.match(dispatch, /Every registered GitHub workflow contributes its configured capacity[\s\S]*Re-read this set on every cycle/)
  assert.match(dispatch, /from drive_agents where provider='github_actions' and status<>'disabled'/)
  assert.match(dispatch, /const workflowKey = `\$\{account\}\/\$\{String\(agent\.github_repo_name\)/)
  assert.match(dispatch, /workflowRuns\.add\(`pending:\$\{intent\.rows\[0\]\.id\}`\)/)
})

test('migration accounting keeps source totals and counts actual outcomes separately', () => {
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const poolRoute = read('src/app/api/migrations/[id]/worker-pool/route.ts')

  assert.match(runtime, /sourceObjectCount = allSourceObjects\.length/)
  assert.match(runtime, /processedFiles: transferred \+ failed \+ skipped,\s*totalFiles: sourceObjectCount/)
  assert.match(runtime, /skipped = sourceObjectCount/)
  assert.match(orchestrator, /transferred_objects/)
  assert.match(orchestrator, /result->'items'->0->>'skipped'/)
  assert.match(orchestrator, /result->'items'->0->>'failed'/)
  assert.match(poolRoute, /transferred_objects/)
  assert.match(poolRoute, /failed_objects/)
})

test('orchestrator continuously maintains every registered workflow instance', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  assert.match(orchestrator, /where provider='github_actions' and status<>'disabled'/)
  assert.match(orchestrator, /MAX_GITHUB_WORKFLOW_WORKERS = 5/)
  assert.match(orchestrator, /activeByWorkflow/)
  assert.match(orchestrator, /Stale GitHub worker canceled before replacement dispatch/)
  assert.match(orchestrator, /async function abortMigrationWorkers/)
  assert.match(orchestrator, /m\.status in\('canceled','completed','aborted'\)/)
  assert.match(orchestrator, /await abortMigrationWorkers\(db, migration\.id/)
  assert.match(orchestrator, /payload->>'workerInstanceId'/)
  assert.doesNotMatch(orchestrator, /const ids = Array\.isArray\(opts\(migration\)\.workerAgentIds\)/)
  assert.match(runtime, /getArg\("poll-ms", "1000"\)/)
})

test('worker job details live only below their migration route', () => {
  assert.equal(fs.existsSync('src/app/dashboard/workers/jobs/[id]/page.tsx'), false)
  assert.equal(fs.existsSync('src/app/dashboard/migrations/[id]/jobs/[jobId]/page.tsx'), true)
  const migrationDetails = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.doesNotMatch(migrationDetails, /dashboard\/workers\/jobs\//)
})

test('migration details never regress worker counters on refresh or reconnect', () => {
  const detailsPage = read('src/app/dashboard/migrations/[id]/page.tsx')
  const bucketState = read('src/lib/migration-bucket-state.ts')
  const migrationOrchestrator = read('workers/migration-orchestrator/src/index.ts')
  const backendReconciler = read('src/app/api/internal/backend-orchestrator/reconcile/route.ts')
  const itemActionRoute = read('src/app/api/migrations/[id]/items/[itemId]/action/route.ts')
  assert.match(detailsPage, /const sameWorkerGeneration =/)
  assert.match(detailsPage, /prevGeneration === nextGeneration/)
  assert.match(detailsPage, /totalObjects: Math\.max\(prevLive\.totalObjects, nextLive\.totalObjects\)/)
  assert.match(detailsPage, /transferredBytes:[\s\S]*Math\.max\(prevLive\.transferredBytes, nextLive\.transferredBytes\)/)
  assert.match(bucketState, /live\.workerStage === "migration" \|\| live\.workerStage === "verification"/)
  assert.match(migrationOrchestrator, /async function refreshSuperSlurperProgress/)
  assert.match(migrationOrchestrator, /slurper\/jobs\/\$\{encodeURIComponent\(item\.slurper_job_id\)\}\/progress/)
  assert.match(migrationOrchestrator, /drive_migration_verification_state/)
  assert.doesNotMatch(backendReconciler, /syncMigrationLiveState|listMigrations/)
  assert.doesNotMatch(detailsPage, /syncMigrationLiveState/)
  assert.match(itemActionRoute, /queueMigrationItemVerification\(id, item\.id, verificationGeneration\)/)
  assert.doesNotMatch(itemActionRoute, /runBucketScanBatch|r2ListAllObjects|r2HeadObject|createInitialBucketVerifyState/)
})

test('file scanner comparison binds UUID and text parameters explicitly', () => {
  const scanner = read('workers/file-scanner/src/index.ts')
  assert.match(scanner, /migration_item_id=\$1::uuid/)
  assert.match(scanner, /j\.payload->'itemIds'->>0=\$1::text/)
  assert.match(scanner, /j\.migration_id=\$9::uuid/)
  assert.match(scanner, /not s\.is_dir_marker/)
  assert.match(scanner, /not d\.is_dir_marker/)
})

test('worker verification can be rerun for failed buckets while migration continues', () => {
  const action = read('src/app/api/migrations/[id]/action/route.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(action, /current\.status in\('failed','completed'\)/)
  assert.match(action, /migration\.status === "running" \? "running" : "verifying"/)
  assert.match(details, /!settingsSyncFailed && effectiveMigrationStatus !== "completed" && \(hasVerificationFailure \|\| overviewProgress\.verifyIssues > 0\)/)
  assert.doesNotMatch(details, /workerPoolMigration && \(hasVerificationFailure \|\| allBucketsTerminal/)
})

test('verified bucket settings respect strict destination verification', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /and \(v\.extra_objects=0 or \$2=false\)/)
  assert.match(orchestrator, /add column if not exists attempt_generation integer/)
  assert.match(orchestrator, /where drive_migration_verification_state\.generation<>excluded\.generation/)
})

test('orchestrator persists bucket stage and settings events for migration logs', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(orchestrator, /async function recordItemStageEvents/)
  assert.match(orchestrator, /'File Scanner verification passed; bucket migration completed'/)
  assert.match(orchestrator, /'Bucket settings synchronized after successful verification'/)
  assert.match(orchestrator, /await recordItemStageEvents\(db, migration, shards\.generation\)/)
  assert.doesNotMatch(details, /files completed`/)
})

test('verification failure stays distinct from transfer failure and is recoverable', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const scanner = read('workers/file-scanner/src/index.ts')
  const action = read('src/app/api/migrations/[id]/items/[itemId]/action/route.ts')
  const migrationAction = read('src/app/api/migrations/[id]/action/route.ts')
  const store = read('src/lib/migrations-store.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const migrations = read('src/app/dashboard/migrations/page.tsx')
  const readOnly = read('src/lib/migration-read-only.ts')

  assert.match(orchestrator, /status='verification_failed',sync_status='failed',sync_message=\$2/)
  assert.match(orchestrator, /slurper_status='verification_failed'/)
  assert.match(orchestrator, /when 'verification_failed' then coalesce\([\s\S]*missing_objects/)
  assert.match(orchestrator, /await recordItemStageEvents\(db, migration, 1\)/)
  assert.match(orchestrator, /Super Slurper transfer completed; File Scanner verification pending/)
  assert.doesNotMatch(orchestrator, /when 'completed' then 'Bucket migration completed'/)
  assert.match(scanner, /phase=\$9::text,status='pending',attempt_count=0,last_error=null/)
  assert.match(scanner, /mismatched_objects=c\.mismatched,extra_objects=c\.extra,attempt_count=0,last_error=null/)
  assert.match(action, /s === "verification_failed"/)
  assert.match(store, /slurper_status='verifying'/)
  assert.match(store, /Manual File Scanner verification requested/)
  assert.match(details, /normalizedDisplayStatus === "verification_failed"/)
  assert.match(details, /verificationWasExplicitlyRequeued/)
  assert.match(details, /normalizedDisplayStatus !== "verification_failed" && \(verifyStatus === "error"/)
  assert.match(details, /!\["completed", "failed"\]\.includes\(String\(effectiveMigrationStatus\)\)/)
  assert.match(details, /effectiveMigrationStatus !== "verification_failed" \?/)
  assert.match(details, /rawMessage === "Bucket migration completed"[\s\S]*File Scanner verification pending/)
  assert.match(migrations, /s === "verification_failed".*Verification failed/)
  assert.match(readOnly, /"completed", "failed", "verification_failed", "canceled"/)
  assert.match(migrationAction, /isCompletedStatus\(i\.slurperStatus\) \|\| normalizeStatus\(i\.slurperStatus\) === "verification_failed"/)
  assert.match(details, /!settingsSyncFailed && effectiveMigrationStatus !== "completed" && \(hasVerificationFailure \|\| overviewProgress\.verifyIssues > 0\)/)
  assert.match(details, /allBucketsTerminal && !\["completed", "failed"\]\.includes\(String\(effectiveMigrationStatus\)\)/)
  assert.match(details, /migration\.status !== "completed" && \(workerPoolMigration/)
  assert.match(action, /!isCompletedStatus\(item\.slurperStatus\) && normalizeStatus\(item\.slurperStatus\) !== "verification_failed"/)
})

test('Super Slurper roll-up distinguishes transfer failures from completed transfers awaiting or failing verification', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /count\(\*\) filter\(where slurper_status in\('completed','verifying','verification_failed','no_files'\)\)::int completed/)
  assert.match(orchestrator, /count\(\*\) filter\(where slurper_status in\('failed','aborted','precheck_failed','bucket_create_failed'\)\)::int failed/)
  assert.match(orchestrator, /const verification = Number\(slurper\.total\) > 0 && Number\(slurper\.completed\) === Number\(slurper\.total\)[\s\S]*?await finishOrRepair\(db, migration, 1\)/)
  assert.match(orchestrator, /'stage',case when \$2='completed' then 'super_slurper_transfer'/)
})

test('worker-pool scanner resumes transient failed inventories and fences API claims to active generation', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const worker = read('workers/migration-worker/migration-worker.mjs')
  assert.match(orchestrator, /function isTransientWorkerError/)
  assert.match(orchestrator, /if \(scan\?\.status === "failed"\)[\s\S]*?isTransientWorkerError\(message\)[\s\S]*?status='pending',lease_owner=null,lease_expires_at=null/)
  assert.match(orchestrator, /File Scanner source inventory failed for/)
  assert.match(orchestrator, /select options,status from drive_migrations where id=\$1 and \(\$2::boolean=false or coalesce\(options->>'executionMode',''\)='migration_workers'\) for update/)
  assert.match(orchestrator, /migration:\$\{migrationId\}:generation:\$\{generation\}:inventory:%/)
  assert.match(orchestrator, /claim_token=\$8::uuid/)
  assert.match(worker, /claimToken: jobClaimTokens\.get\(jobId\)/)
  assert.match(worker, /claimed\?\.job\?\.id && typeof claimed\.job\.claimToken === "string"/)
  assert.match(orchestrator, /!\["running", "verifying"\]\.includes\(String\(migration\.status\)\)/)
})

test('Migration Orchestrator migration selector binds its transient-error pattern to the only supplied parameter', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const selector = orchestrator.slice(orchestrator.indexOf('async function selectMigration'), orchestrator.indexOf('async function mapWithConcurrency'))
  assert.match(selector, /s\.error ~\* \$1/)
  assert.match(selector, /v\.last_error ~\* \$1/)
  assert.match(selector, /\[TRANSIENT_SCAN_SQL_PATTERN\]/)
  assert.doesNotMatch(selector, /~\* \$2/)
})

test('Super Slurper repair re-enters the shared worker-pool scan, queue, copy, and verification lifecycle', () => {
  const action = read('src/app/api/migrations/[id]/action/route.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  const route = read('src/app/api/migrations/[id]/route.ts')
  const stream = read('src/app/api/migrations/[id]/stream/route.ts')
  const runtime = read('workers/migration-worker/migration-worker.mjs')

  assert.match(action, /executionMode: "migration_workers"/)
  assert.match(action, /workerGeneration: nextGeneration/)
  assert.match(action, /overwrite: false/)
  assert.match(action, /workerRepairMismatchedObjects: false/)
  assert.match(action, /wakeMigrationOrchestrator\(\)/)
  assert.match(action, /File Scanner must be configured and enabled/)
  assert.match(runtime, /workerRepairMismatchedObjects === true/)
  assert.match(runtime, /inspectAssignedObjects\(sourceClient, targetClient/)
  assert.match(runtime, /sourceSha256 === destinationSha256/)
  assert.match(details, /Repair with worker pool/)
  assert.doesNotMatch(details, /Run with worker|workersOpen|Worker Overview|repair_and_verify/)
  assert.doesNotMatch(route, /listRepairJobsByMigration/)
  assert.doesNotMatch(stream, /listRepairJobsByMigration/)
})

test('worker-pool repair stays queued until the orchestrator durably creates a scanner task', () => {
  const action = read('src/app/api/migrations/[id]/action/route.ts')
  const reservation = action.slice(action.indexOf('async function reserveMigrationWorkerGeneration'), action.indexOf('async function waitForOrchestratorCycleToRelease'))
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(reservation, /slurper_status='queued'/)
  assert.match(reservation, /'stage','awaiting_source_scan'/)
  assert.match(reservation, /migrationInventory.*'status','pending'/)
  assert.match(reservation, /r\.status in\('pending','running'\)/)
  assert.match(reservation, /drive_migration_orchestrator_state/)
  assert.match(details, /Retry with worker pool/)
  assert.match(details, /effectiveMigrationStatus === "canceled"/)
})

test('worker-pool queue failures cannot be mistaken for an empty successful migration', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  assert.match(orchestrator, /if \(objects > 0\)[\s\S]*?queue_materialization_failed[\s\S]*?status='failed'[\s\S]*?terminalFailure: true/)
  assert.match(orchestrator, /work_key like \$2[\s\S]*?generation:\$\{generation\}:inventory/)
  assert.match(orchestrator, /Superseded migration worker-pool generation; dispatch skipped/)
})

test('worker-pool repair reconciles destinations before copy and bucket preparation stays worker-owned', () => {
  const runtime = read('workers/migration-worker/migration-worker.mjs')
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const startRoute = read('src/app/api/migrations/[id]/start/route.ts')
  assert.match(startRoute, /Queued for Migration Orchestrator/)
  assert.match(startRoute, /await wakeMigrationOrchestrator\(\)/)
  assert.doesNotMatch(startRoute, /r2ListBuckets|r2CreateBucketViaApi|ensureTargetBucketExists|slurperCreateJob|slurperGetActiveJobCount/)
  assert.doesNotMatch(startRoute, /executionMode === "migration_workers"/)
  assert.match(orchestrator, /async function ensureWorkerTargetBuckets/)
  assert.match(orchestrator, /await ensureWorkerTargetBuckets\(db, migration, generation\)/)
  assert.match(runtime, /const \[sourceSha256, destinationSha256\] = await Promise\.all/)
  assert.match(runtime, /sourceSha256 === destinationSha256/)
  assert.match(runtime, /const toRepair = overwrite && payload\.job\.mode !== "verify_only"/)
  assert.match(runtime, /alreadyPresent = overwrite \? 0 : Math\.max\(0, sourceObjects\.length - diffCandidates\.length\)/)
  assert.match(runtime, /already verified, \$\{initialMissing\} missing/)
  assert.ok(runtime.indexOf('const [sourceSha256, destinationSha256]') < runtime.indexOf('if (isMismatch && !overwrite)'), 'destination integrity checks must run before the overwrite setting is applied')
  assert.match(runtime, /if \(!overwrite && !isMismatch && latestTargetSize === objectSize\)/)
  assert.match(orchestrator, /'transferredObjects',least\(coalesce\(i\.source_objects,0\)/)
  assert.match(orchestrator, /await ensureBucketVerification\(db, migration, shards\.generation\)/)
})

test('verification lifecycle logs use the durable scanner state and bind events to a verification attempt', () => {
  const orchestrator = read('workers/migration-orchestrator/src/index.ts')
  const store = read('src/lib/migrations-store.ts')
  const details = read('src/app/dashboard/migrations/[id]/page.tsx')
  assert.match(orchestrator, /when v\.status in\('pending','running'\) then 'verifying'[\s\S]*?when v\.status='completed' then 'completed'/)
  assert.match(orchestrator, /'generation',p\.verification_generation,'attemptId',p\.verification_attempt_id/)
  assert.match(orchestrator, /workerEventAttemptId/)
  assert.match(store, /returning i\.id,a\.attempt_id/)
  assert.match(details, /eventAttemptId !== undefined && currentVerificationAttemptId !== undefined && eventAttemptId !== currentVerificationAttemptId/)
})
