const { test } = process.getBuiltinModule("node:test")
const assert = process.getBuiltinModule("node:assert/strict")
const fs = process.getBuiltinModule("node:fs")
const path = process.getBuiltinModule("node:path")

const root = path.resolve(__dirname, "..")
const read = (file) => fs.readFileSync(path.join(root, file), "utf8")

test("dashboard data stores use the shared PostgreSQL layer without Supabase clients", () => {
  for (const file of [
    "src/lib/accounts-store.ts",
    "src/lib/ambient-theme-store.ts",
    "src/lib/agents-store.ts",
    "src/lib/bucket-scan-store.ts",
    "src/lib/bucket-stats-store.ts",
    "src/lib/migration-failure-records-store.ts",
    "src/lib/migrations-store.ts",
    "src/lib/repair-jobs-store.ts",
    "src/lib/users-store.ts",
    "src/lib/email-verification.ts",
    "src/lib/sms-verification.ts",
  ]) {
    const source = read(file)
    assert.match(source, /from ["']\.\/db["']|from ["']@\/lib\/db["']/)
    assert.doesNotMatch(source, /getSupabaseServerClient|@supabase\/supabase-js/)
  }

  const analytics = read("src/app/api/dashboard/analytics/route.ts")
  assert.match(analytics, /from ["']@\/lib\/db["']/)
  assert.doesNotMatch(analytics, /getSupabaseServerClient|@supabase\/supabase-js/)
  const accounts = read("src/lib/accounts-store.ts")
  assert.match(accounts, /export async function updateAccount[\s\S]*withDbTransaction/)
  assert.match(accounts, /export async function deleteAccount[\s\S]*withDbTransaction/)
  const emailVerification = read("src/lib/email-verification.ts")
  const smsVerification = read("src/lib/sms-verification.ts")
  assert.match(emailVerification, /crypto\.timingSafeEqual/)
  assert.match(smsVerification, /crypto\.timingSafeEqual/)
  assert.match(read("src/app/layout.tsx"), /const ambientThemeSettings = await getAmbientThemeSettings\(\)/)
})

test("repair worker claims are atomic and dashboard reads do not reconcile against GitHub", () => {
  const source = read("src/lib/repair-jobs-store.ts")
  assert.match(source, /for update\s+skip locked/i)
  assert.match(source, /returning job\.\*/i)
  assert.match(source, /export async function listRepairJobs\(limit = 50\): Promise<DriveRepairJob\[]> \{\s+return listRepairJobsRaw\(limit\)/)
  assert.match(source, /export async function getRepairJob\(id: string\): Promise<DriveRepairJob \| null> \{\s+return getRepairJobRaw\(id\)/)
})

test("runtime PostgreSQL uses only POSTGRES_URL and keeps the process pool bounded", () => {
  const source = read("src/lib/db.ts")
  assert.match(source, /const connectionString = getEnv\("POSTGRES_URL"\)/)
  assert.match(source, /connectionString,\s*ssl: buildSslConfig\(\)/)
  assert.match(source, /return Boolean\(getEnv\("POSTGRES_URL"\)\)/)
  assert.match(source, /var __drivePgAdvisoryLockPool: Pool \| undefined/)
  assert.match(source, /const client = await global\.__drivePgAdvisoryLockPool\.connect\(\)/)
  assert.match(source, /process\.env\.NODE_ENV === "production" \? 2 : 1/)
  assert.match(source, /getEnv\("POSTGRES_SSL"\).*\?\? true/)
  assert.match(source, /getEnv\("DISABLE_POSTGRES_SSL"\).*\?\? false/)
  assert.match(source, /getEnv\("POSTGRES_SLOW_QUERY_MS"\)/)
  assert.match(source, /SLOW_QUERY_LOG_WINDOW_MS = 30_000/)
  assert.match(source, /pool\.waitingCount/)
  assert.match(source, /console\.warn\("\[postgres\] slow query summary"/)
  assert.match(source, /suppressedSlowQueries: suppressedSlowQueryCount/)
  const slowLog = source.match(/console\.warn\("\[postgres\] slow query summary",\s*\{[\s\S]*?\n\s*\}\)/)
  assert.ok(slowLog, "expected structured slow-query pool diagnostics")
  assert.doesNotMatch(slowLog[0], /\b(text|params):/)
  for (const route of [
    "src/app/api/internal/backend-orchestrator/config/route.ts",
    "src/app/api/internal/file-scanner/config/route.ts",
    "src/app/api/internal/migration-orchestrator/config/route.ts",
  ]) {
    assert.match(read(route), /process\.env\.POSTGRES_URL/)
  }
  const backendWorker = read("workers/backend-orchestrator/src/index.ts")
  assert.match(backendWorker, /ssl:\s*disablePostgresSsl\s*\?\s*false\s*:\s*\{\s*rejectUnauthorized:\s*false\s*\}/)
  assert.doesNotMatch(backendWorker, /isSupabase|supabase\.com/)
  const schemaInstaller = read("scripts/prepare-schema.mjs")
  assert.doesNotMatch(schemaInstaller, /supabase\.co|prefersDirectSupabase/i)
  assert.match(schemaInstaller, /const url = value\("POSTGRES_URL"\)/)
  assert.match(schemaInstaller, /Set POSTGRES_URL in the build environment/)
  assert.match(schemaInstaller, /booleanValue\("DISABLE_POSTGRES_SSL", false\)/)
})

test("users page is server-paginated with safe columns and analytics reads only user aggregates", () => {
  const usersStore = read("src/lib/users-store.ts")
  const pagedUsers = usersStore.match(/export async function listUsersPage\([\s\S]*?\n}\n\nexport async function hasAnyUsers/)
  assert.ok(pagedUsers, "expected a bounded users-page query")
  assert.match(pagedUsers[0], /limit greatest\(0,/i)
  assert.match(pagedUsers[0], /order by u\.created_at asc,u\.id asc/i)
  assert.match(pagedUsers[0], /count\(\*\) filter \(where status='active'\)/i)
  assert.doesNotMatch(pagedUsers[0], /select\s+\*\s+from\s+public\.drive_users|password_hash|totp_secret/i)
  assert.doesNotMatch(usersStore, /export async function (getAllUsers|searchUsers)\(/)

  const usersRoute = read("src/app/api/users/route.ts")
  assert.match(usersRoute, /listUsersPage\(/)
  assert.match(usersRoute, /searchParams\.get\("page"\)/)
  assert.match(usersRoute, /searchParams\.get\("limit"\)/)

  const analytics = read("src/app/api/dashboard/analytics/route.ts")
  assert.match(analytics, /getUserSummary/)
  assert.match(analytics, /listDashboardAccountSummaries/)
  assert.doesNotMatch(analytics, /getAllAccounts/)
  assert.doesNotMatch(analytics, /getAllUsers|type User from ["']@\/lib\/users-store/)
  const repairProjection = analytics.match(/selectRows<AnalyticsRepairJobRow>\([\s\S]*?\n\s*100\n\s*\)/)
  assert.ok(repairProjection, "expected a bounded repair-job analytics projection")
  assert.match(repairProjection[0], /id,migration_id,status,summary,error,completed_at,created_at,updated_at/)
  assert.doesNotMatch(repairProjection[0], /payload|progress|result/)
  assert.match(analytics, /itemMetricsByDay/)
  assert.doesNotMatch(analytics, /itemRowsAsItems\.filter\(|migrations\.filter\(\(m\) => dateKey/)
  assert.doesNotMatch(analytics, /Math\.min\(\.\.\.times\)/)
})

test("analytics aggregates bucket and verification summaries in one database round trip", () => {
  const analytics = read("src/app/api/dashboard/analytics/route.ts")
  const summaryStart = analytics.indexOf("async function getAnalyticsSqlSummary()")
  const summaryEnd = analytics.indexOf("async function listActiveAccountSnapshots()", summaryStart)
  assert.ok(summaryStart >= 0 && summaryEnd > summaryStart, "expected the consolidated analytics query")
  const summary = analytics.slice(summaryStart, summaryEnd)
  assert.equal((summary.match(/queryDb</g) ?? []).length, 1)
  assert.match(summary, /bucket_status_counts as/i)
  assert.match(summary, /join active_account/i)
  assert.match(summary, /order by created_at desc\s+limit 25/i)
  assert.match(summary, /order by updated_at desc nulls first[\s\S]*?limit 10/i)
  assert.match(summary, /drive_migration_item_failure_records/i)
  assert.match(summary, /count\(\*\)::text from public\.drive_bucket_verify_diffs/i)
  assert.match(summary, /effective_agents as materialized/i)
  assert.match(summary, /worker_status_counts as/i)
  assert.match(summary, /worker_total_count/i)
  assert.match(summary, /online_worker_count/i)
  assert.match(analytics, /ANALYTICS_ITEM_PROGRESS_SQL/)
  assert.match(analytics, /\$\{ANALYTICS_ITEM_PROGRESS_SQL\} as progress/)
  assert.match(analytics, /coalesce\(last_progress_at,updated_at,created_at\) >= \$1/)
  assert.match(analytics, /listAnalyticsMigrationItems\(start, days === null\)/)
  assert.doesNotMatch(analytics, /selectRows<BucketStatsRow>/)
  assert.doesNotMatch(analytics, /countRows\(/)
})

test("analytics worker metrics share the grouped summary query without full agent or run records", () => {
  const analytics = read("src/app/api/dashboard/analytics/route.ts")
  const summaryStart = analytics.indexOf("async function getAnalyticsSqlSummary()")
  const summaryEnd = analytics.indexOf("async function listActiveAccountSnapshots()", summaryStart)
  assert.ok(summaryStart >= 0 && summaryEnd > summaryStart, "expected worker counts in the consolidated analytics query")
  const summary = analytics.slice(summaryStart, summaryEnd)
  assert.equal((summary.match(/queryDb</g) ?? []).length, 1)
  assert.match(summary, /from public\.drive_agents/i)
  assert.match(summary, /interval '90 seconds'/i)
  assert.match(summary, /interval '60 seconds'/i)
  assert.match(summary, /jsonb_object_agg\(effective_status,count\)/i)
  assert.doesNotMatch(summary, /drive_agent_runs|select\s+a\.\*/i)
  assert.doesNotMatch(analytics, /listAgents|DriveAgentRun/)
})

test("bucket dashboard reads only the selected account summary instead of loading account secrets", () => {
  const accounts = read("src/lib/accounts-store.ts")
  const summaryReader = accounts.match(/export async function getActiveDashboardAccountSummary\(\)[\s\S]*?\n}/)
  assert.ok(summaryReader, "expected a projected active-account read")
  assert.match(summaryReader[0], /where status='active'/)
  assert.match(summaryReader[0], /order by updated_at desc nulls last,created_at desc,id desc/)
  assert.doesNotMatch(summaryReader[0], /api_token|r2_secret_access_key|password/)

  const bucketsRoute = read("src/app/api/buckets/route.ts")
  const bucketsGet = bucketsRoute.slice(bucketsRoute.indexOf("export async function GET"), bucketsRoute.indexOf("export async function POST"))
  assert.match(bucketsGet, /getBucketDashboardBootstrap\(\)/)
  assert.doesNotMatch(bucketsGet, /listBucketSettingsSnapshots|listBucketDeliverySettings|listAssignedProjectsForBuckets|listProjectDeliverySettings|r2List/)

  const storageRoute = read("src/app/api/storage/buckets/route.ts")
  const storageGet = storageRoute.slice(storageRoute.indexOf("export async function GET"), storageRoute.indexOf("export async function POST"))
  assert.match(storageGet, /getActiveDashboardAccountSummary\(\)/)
  assert.doesNotMatch(storageGet, /getAllAccounts\(\)/)

  const bootstrap = read("src/lib/bucket-dashboard-store.ts")
  const bootstrapFunction = bootstrap.match(/export async function getBucketDashboardBootstrap\(\)[\s\S]*?\n}/)
  assert.ok(bootstrapFunction, "expected a single-query bucket dashboard bootstrap")
  assert.equal((bootstrapFunction[0].match(/queryDb</g) ?? []).length, 1)
  assert.match(bootstrapFunction[0], /drive_bucket_settings_snapshots/)
  assert.match(bootstrapFunction[0], /drive_bucket_stats/)
  assert.match(bootstrapFunction[0], /drive_bucket_delivery_settings/)
  assert.match(bootstrapFunction[0], /drive_project_delivery_settings/)

  const accountStore = accounts.match(/export async function getActiveAccountR2Credentials\(\)[\s\S]*?\n}/)
  assert.ok(accountStore, "expected a dedicated R2-credentials projection")
  assert.match(accountStore[0], /select id,status,cloudflare_account_id,r2_access_key_id,r2_secret_access_key/)
  assert.doesNotMatch(accountStore[0], /select \*|api_token|password|two_factor_secret/)
  assert.match(read("src/app/api/storage/buckets/route.ts"), /getActiveAccountR2Credentials\(\)/)
})

test("account list pages load safe projections and fetch credentials only on explicit detail actions", () => {
  const accountList = read("src/app/api/accounts/route.ts")
  const accountDetail = read("src/app/api/accounts/[id]/route.ts")
  const page = read("src/app/dashboard/accounts/page.tsx")
  assert.match(accountList, /listDashboardAccountSummaries\(\)/)
  assert.doesNotMatch(accountList, /getAllAccounts\(\)/)
  assert.match(accountDetail, /requireAdmin\(\)[\s\S]*?getAccountById\(id\)/)
  assert.match(accountDetail, /Cache-Control.*no-store/)
  assert.doesNotMatch(accountDetail, /getAllAccounts\(\)/)
  assert.match(accountDetail, /before: before \? \{ account: toDashboardAccountSummary\(before\) \}/)
  assert.match(page, /dashboard:accounts:v2/)
  assert.match(page, /password: ""[\s\S]*?twoFactorSecret: ""[\s\S]*?apiToken: ""/)
  assert.match(page, /fetch\(`\/api\/accounts\/\$\{encodeURIComponent\(account\.id\)\}`/)
  assert.match(page, /openViewAccount\(account\)/)
  assert.match(page, /openSettingsAccount\(account\)/)
})

test("migrations page bootstrap uses one safe, database-snapshot endpoint", () => {
  const route = read("src/app/api/migrations/route.ts")
  const getStart = route.indexOf("export async function GET()")
  const getEnd = route.indexOf("export async function POST(", getStart)
  assert.ok(getStart >= 0 && getEnd > getStart, "expected migrations bootstrap GET")
  const getHandler = route.slice(getStart, getEnd)
  assert.match(getHandler, /getMigrationDashboardBootstrap\(\)/)
  assert.doesNotMatch(getHandler, /listDashboardAccountSummaries|listActiveBucketStats|listMigrationItems\(/)
  assert.match(getHandler, /accounts: accounts\.map\(\(\{ id, label, email, status \}\)/)
  assert.doesNotMatch(getHandler, /apiToken|r2SecretAccessKey|password/)

  const page = read("src/app/dashboard/migrations/page.tsx")
  const loadStart = page.indexOf("const loadAll = React.useCallback")
  const loadEnd = page.indexOf("const confirmDelete =", loadStart)
  assert.ok(loadStart >= 0 && loadEnd > loadStart, "expected migrations dashboard bootstrap")
  const load = page.slice(loadStart, loadEnd)
  assert.equal((load.match(/fetch\(/g) ?? []).length, 1)
  assert.match(load, /fetch\("\/api\/migrations"/)
  assert.doesNotMatch(load, /\/api\/accounts|\/api\/storage\/buckets|\/api\/migrations\/\$\{encodeURIComponent\(current\.id\)\}/)
  assert.doesNotMatch(page, /\/api\/migrations\/\$\{encodeURIComponent\([^)]*\)\}\/sync/)

  const startRoute = read("src/app/api/migrations/[id]/start/route.ts")
  assert.match(startRoute, /async function wakeMigrationOrchestrator[\s\S]*?\/wake/)
  assert.doesNotMatch(startRoute, /\/run`/)

  const migrationsStore = read("src/lib/migrations-store.ts")
  const bootstrapStart = migrationsStore.indexOf("export async function getMigrationDashboardBootstrap(")
  const bootstrapEnd = migrationsStore.indexOf("export async function listMigrationsByAccount(", bootstrapStart)
  assert.ok(bootstrapStart >= 0 && bootstrapEnd > bootstrapStart)
  const bootstrap = migrationsStore.slice(bootstrapStart, bootstrapEnd)
  assert.equal((bootstrap.match(/queryDb</g) ?? []).length, 1)
  assert.match(bootstrap, /jsonb_agg/)
  assert.match(bootstrap, /current_migration/)
  assert.match(bootstrap, /drive_bucket_stats/)
  assert.match(bootstrap, /drive_migration_items/)
  assert.doesNotMatch(bootstrap, /api_token|r2_secret_access_key|password/)
})

test("migration detail bootstrap loads safe account options with its initial payload", () => {
  const route = read("src/app/api/migrations/[id]/route.ts")
  const getStart = route.indexOf("export async function GET(")
  const deleteStart = route.indexOf("export async function DELETE(", getStart)
  assert.ok(getStart >= 0 && deleteStart > getStart)
  const getHandler = route.slice(getStart, deleteStart)
  assert.match(getHandler, /getMigrationDetailBootstrap\(id\)/)
  assert.match(getHandler, /const \{ migration, items, workerRuns, accounts \} = bootstrap/)
  assert.doesNotMatch(getHandler, /listDashboardAccountSummaries|listMigrationWorkerRuns|listMigrationItems/)
  assert.doesNotMatch(getHandler, /apiToken|r2SecretAccessKey|password/)

  const store = read("src/lib/migrations-store.ts")
  const bootstrapStart = store.indexOf("export async function getMigrationDetailBootstrap(")
  const bootstrapEnd = store.indexOf("export async function listMigrationItems(", bootstrapStart)
  assert.ok(bootstrapStart >= 0 && bootstrapEnd > bootstrapStart)
  const detailBootstrap = store.slice(bootstrapStart, bootstrapEnd)
  assert.equal((detailBootstrap.match(/queryDb</g) ?? []).length, 1)
  assert.match(detailBootstrap, /drive_migration_items/)
  assert.match(detailBootstrap, /drive_agent_runs/)
  assert.match(detailBootstrap, /drive_accounts/)
  assert.match(detailBootstrap, /job\.id::text=run\.job_reference/)
  assert.match(detailBootstrap, /'current_file'/)
  assert.match(detailBootstrap, /as resolved_summary_item_count/i)
  assert.match(detailBootstrap, /as resolved_summary_objects/i)
  assert.match(detailBootstrap, /as resolved_summary_bytes/i)
  assert.match(detailBootstrap, /case when \$2::boolean then coalesce/i)
  assert.doesNotMatch(detailBootstrap, /'job_payload'|'job_progress'/)

  const page = read("src/app/dashboard/migrations/[id]/page.tsx")
  const loadStart = page.indexOf("const loadInitial = React.useCallback")
  const loadEnd = page.indexOf("const runMigrationAction =", loadStart)
  assert.ok(loadStart >= 0 && loadEnd > loadStart)
  const load = page.slice(loadStart, loadEnd)
  assert.equal((load.match(/fetch\(/g) ?? []).length, 1)
  assert.match(load, /detailsJson\.accounts/)
  assert.doesNotMatch(load, /\/api\/accounts/)
  assert.doesNotMatch(page, /\/api\/migrations\/\$\{encodeURIComponent\([^)]*\)\}\/sync/)
})

test("explicit migration retries wake the orchestrator after durable state changes", () => {
  const migrationAction = read("src/app/api/migrations/[id]/action/route.ts")
  const itemAction = read("src/app/api/migrations/[id]/items/[itemId]/action/route.ts")
  assert.match(migrationAction, /action === "retry_migration"[\s\S]*?await updateMigration\(id,[\s\S]*?await wakeMigrationOrchestrator\(\)/)
  assert.match(itemAction, /action === "retry"[\s\S]*?await updateMigration\(id,[\s\S]*?await wakeMigrationOrchestrator\(\)/)
})

test("API usage aggregates are page-stable and use one bounded database request", () => {
  const operations = read("src/lib/project-operations-store.ts")
  const start = operations.indexOf("export async function getProjectApiUsage(")
  const end = operations.indexOf("export async function createProjectOperationJob(", start)
  assert.ok(start >= 0 && end > start, "expected the API usage store")
  const usage = operations.slice(start, end)
  assert.equal((usage.match(/queryDb</g) ?? []).length, 1)
  assert.match(usage, /filtered_events as materialized/i)
  assert.match(usage, /const filterWhere = filterClauses/)
  assert.match(usage, /const pageClauses = \[\.\.\.filterClauses\]/)
  assert.match(usage, /pageClauses\.push\(`\(e\.occurred_at, e\.id\)/)
  assert.match(operations, /drive_project_api_events_occurred_id_idx/)
})

test("project details read synchronized bucket snapshots without per-bucket provider calls", () => {
  const route = read("src/app/api/projects/[id]/route.ts")
  const start = route.indexOf("export async function GET(")
  const end = route.indexOf("export async function PATCH(", start)
  assert.ok(start >= 0 && end > start, "expected the project details GET handler")
  const getHandler = route.slice(start, end)
  assert.match(getHandler, /getProjectDetailBootstrap\(id\)/)
  assert.match(getHandler, /bootstrap\.bucketDetails/)
  assert.doesNotMatch(getHandler, /listBucketSettingsSnapshots|listBucketDeliverySettings|listAssignedProjectsForBuckets|listProjectDeliverySettings/)
  assert.doesNotMatch(getHandler, /getActiveAccount\(/)
  assert.doesNotMatch(getHandler, /getActiveAccountId\(|listProjectBucketsById\(/)
  assert.doesNotMatch(getHandler, /readBucketSettings|upsertBucketSettingsSnapshot|getEffectiveBucketMediaOrigins\(/)
  assert.doesNotMatch(getHandler, /Promise\.all\(scopedBuckets\.map/)

  const projects = read("src/lib/projects-store.ts")
  const bootstrapStart = projects.indexOf("export async function getProjectDetailBootstrap(")
  const bootstrapEnd = projects.indexOf("export async function createProjectRecord(", bootstrapStart)
  assert.ok(bootstrapStart >= 0 && bootstrapEnd > bootstrapStart, "expected one project-detail bootstrap query")
  const bootstrapQuery = projects.slice(bootstrapStart, bootstrapEnd)
  assert.equal((bootstrapQuery.match(/queryDb</g) ?? []).length, 1)
  assert.match(bootstrapQuery, /active_account_id/)
  assert.match(bootstrapQuery, /assigned_buckets/)
  assert.match(bootstrapQuery, /jsonb_agg/)
  assert.match(bootstrapQuery, /drive_bucket_settings_snapshots/)
  assert.match(bootstrapQuery, /drive_bucket_delivery_settings/)
  assert.match(bootstrapQuery, /drive_project_delivery_settings/)
})

test("project bucket subpage loads its project, assignments, and available names in one database query", () => {
  const projects = read("src/lib/projects-store.ts")
  const start = projects.indexOf("export async function getProjectBucketManagementData(")
  const end = projects.indexOf("export async function getProjectBucketAssignment(", start)
  assert.ok(start >= 0 && end > start, "expected the project bucket management query")
  const query = projects.slice(start, end)
  assert.equal((query.match(/queryDb</g) ?? []).length, 1)
  assert.match(query, /drive_project_bucket_assignments/)
  assert.match(query, /drive_bucket_stats/)
  assert.match(query, /drive_accounts/)

  const route = read("src/app/api/projects/[id]/buckets/route.ts")
  const handlerStart = route.indexOf("export async function GET(")
  const handlerEnd = route.indexOf("export async function POST(", handlerStart)
  assert.match(route.slice(handlerStart, handlerEnd), /getProjectBucketManagementData\(id\)/)
  assert.doesNotMatch(route.slice(handlerStart, handlerEnd), /r2ListBuckets|listProjectBuckets\(/)

  const page = read("src/app/dashboard/projects/[id]/buckets/page.tsx")
  const loadStart = page.indexOf("const loadAll = React.useCallback")
  const loadEnd = page.indexOf("const validation = React.useMemo", loadStart)
  const load = page.slice(loadStart, loadEnd)
  assert.equal((load.match(/fetch\(/g) ?? []).length, 1)
  assert.doesNotMatch(load, /api\/storage\/buckets/)
})

test("project API-key subpage loads project and keys in one request and one query", () => {
  const page = read("src/app/dashboard/projects/[id]/keys/page.tsx")
  const loadStart = page.indexOf("const loadAll = React.useCallback")
  const loadEnd = page.indexOf("const createKey =", loadStart)
  assert.ok(loadStart >= 0 && loadEnd > loadStart)
  const load = page.slice(loadStart, loadEnd)
  assert.equal((load.match(/fetch\(/g) ?? []).length, 1)
  assert.match(load, /data\.project/)
  assert.match(load, /data\.keys/)

  const route = read("src/app/api/projects/[id]/keys/route.ts")
  const getStart = route.indexOf("export async function GET(")
  const getEnd = route.indexOf("export async function POST(", getStart)
  const getHandler = route.slice(getStart, getEnd)
  assert.match(getHandler, /getProjectKeysBootstrap\(id\)/)
  assert.doesNotMatch(getHandler, /listProjectApiKeys/)

  const projects = read("src/lib/projects-store.ts")
  const storeStart = projects.indexOf("export async function getProjectKeysBootstrap(")
  const storeEnd = projects.indexOf("export async function createProjectApiKey(", storeStart)
  const store = projects.slice(storeStart, storeEnd)
  assert.equal((store.match(/queryDb</g) ?? []).length, 1)
  assert.match(store, /drive_project_api_key_assignments/)
  assert.match(store, /drive_project_api_keys/)
})

test("project stores reuse versioned central schema readiness instead of replaying DDL on each cold instance", () => {
  const projects = read("src/lib/projects-store.ts")
  const start = projects.indexOf("export async function ensureProjectSchema()")
  const end = projects.indexOf("export async function listProjects()", start)
  assert.ok(start >= 0 && end > start, "expected project schema readiness function")
  assert.match(projects.slice(start, end), /await ensureDriveSchema\(\)/)
  assert.doesNotMatch(projects.slice(start, end), /create table|alter table|update drive_projects/)
})

test("migration pages are read-only and explicit verification actions wake only the orchestrator", () => {
  assert.equal(fs.existsSync(path.join(root, "src/app/api/migrations/[id]/sync/route.ts")), false)
  const detailsRoute = read("src/app/api/migrations/[id]/route.ts")
  const detailsGet = detailsRoute.slice(detailsRoute.indexOf("export async function GET("), detailsRoute.indexOf("export async function DELETE("))
  assert.doesNotMatch(detailsGet, /fetch\(|wake|scanBucket|verifyBucket/)

  const migrationAction = read("src/app/api/migrations/[id]/action/route.ts")
  const wakeStart = migrationAction.indexOf("async function wakeMigrationOrchestrator(")
  const wakeEnd = migrationAction.indexOf("async function waitForOrchestratorCycleToRelease(", wakeStart)
  assert.ok(wakeStart >= 0 && wakeEnd > wakeStart)
  const wakeHelper = migrationAction.slice(wakeStart, wakeEnd)
  assert.match(wakeHelper, /settings\.orchestratorUrl[\s\S]*\/wake/)
  assert.doesNotMatch(wakeHelper, /settings\.fileScannerUrl\.replace|fetch\(`\$\{settings\.fileScannerUrl/)
  const workerVerifyStart = migrationAction.indexOf('if (migration.options.executionMode === "migration_workers")', migrationAction.indexOf('if (action === "verify_all")'))
  const workerVerifyEnd = migrationAction.indexOf("const prefix =", workerVerifyStart)
  assert.ok(workerVerifyStart >= 0 && workerVerifyEnd > workerVerifyStart)
  assert.match(migrationAction.slice(workerVerifyStart, workerVerifyEnd), /wakeMigrationOrchestrator\(\{ requireFileScanner: true \}\)/)
  assert.doesNotMatch(migrationAction.slice(workerVerifyStart, workerVerifyEnd), /wakeMigrationService\(|fileScannerUrl.*fetch/)

  const failuresRoute = read("src/app/api/migrations/[id]/items/[itemId]/failures/route.ts")
  assert.match(failuresRoute, /listMigrationItemFailureRecords/)
  assert.doesNotMatch(failuresRoute, /runBucketScanBatch|ensureBucketScan|inferVerifyDiffsFromScans|r2ListAllObjects|probeObject\(/)
  assert.doesNotMatch(read("src/app/dashboard/migrations/[id]/page.tsx"), /failures\?limit=250&refresh=1/)

  const migrationStore = read("src/lib/migrations-store.ts")
  const start = migrationStore.indexOf("export async function getMigration(")
  const end = migrationStore.indexOf("export async function listMigrationItems(", start)
  const getMigration = migrationStore.slice(start, end)
  assert.match(getMigration, /left join lateral/i)
  assert.doesNotMatch(getMigration, /\bupdate\s+public\.drive_migrations/i)
})
